/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "Agent.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nxp_iot_EndpointInformation, nxp_iot_EndpointInformation, AUTO)


PB_BIND(nxp_iot_AgentHelloRequest, nxp_iot_AgentHelloRequest, AUTO)


PB_BIND(nxp_iot_AgentHelloResponse, nxp_iot_AgentHelloResponse, 2)


PB_BIND(nxp_iot_AgentAdditionalData, nxp_iot_AgentAdditionalData, AUTO)


PB_BIND(nxp_iot_AgentClaimStatus, nxp_iot_AgentClaimStatus, AUTO)


PB_BIND(nxp_iot_AgentClaimStatus_DetailedClaimStatus, nxp_iot_AgentClaimStatus_DetailedClaimStatus, AUTO)


PB_BIND(nxp_iot_AgentRtpStatus, nxp_iot_AgentRtpStatus, AUTO)


PB_BIND(nxp_iot_AgentRtpStatus_RtpObjectStatus, nxp_iot_AgentRtpStatus_RtpObjectStatus, AUTO)


PB_BIND(nxp_iot_AgentCspStatus, nxp_iot_AgentCspStatus, AUTO)


PB_BIND(nxp_iot_AgentCspStatus_CspServiceStatus, nxp_iot_AgentCspStatus_CspServiceStatus, AUTO)


PB_BIND(nxp_iot_UpdateStatusReport, nxp_iot_UpdateStatusReport, AUTO)


PB_BIND(nxp_iot_AgentGoodbyeRequest, nxp_iot_AgentGoodbyeRequest, AUTO)


PB_BIND(nxp_iot_AgentCrlRequest, nxp_iot_AgentCrlRequest, AUTO)


PB_BIND(nxp_iot_AgentCrlResponse, nxp_iot_AgentCrlResponse, AUTO)















