/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_AGENT_PB_H_INCLUDED
#define PB_NXP_IOT_AGENT_PB_H_INCLUDED
#include <pb.h>
#include "Types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Indicated the version/structure of the service descriptor that the client is supporting. */
typedef enum _nxp_iot_ServiceDescriptorVersion {
    /* Use c struct for serialization of a service descriptor. This is not supported by the EdgeLock
 2GO cloud service any longer. */
    nxp_iot_ServiceDescriptorVersion_C_STRUCTURE_01 = 0,
    /* Use protobuf encoding for serialization of a service descriptor. */
    nxp_iot_ServiceDescriptorVersion_PROTOBUF = 10
} nxp_iot_ServiceDescriptorVersion;

typedef enum _nxp_iot_AgentHelloRequest_DeviceState {
    /* The state of the configuration of the data managed by EdgeLock 2GO cloud service is OK. 
 A regular check for required updates is done. */
    nxp_iot_AgentHelloRequest_DeviceState_OK = 0,
    /* The EdgeLock 2GO agent reports problems with connecting to a provisioned cloud service to
 the EdgeLock 2GO cloud service. */
    nxp_iot_AgentHelloRequest_DeviceState_CLOUD_ERROR = 10,
    /* Force execution of all actions for a device. This is useful mainly for testing. */
    nxp_iot_AgentHelloRequest_DeviceState_FORCE_UPDATE = 100
} nxp_iot_AgentHelloRequest_DeviceState;

/* By convention status codes < 0x10 indicate success,
 status codes >= 0x10 indicate errors. */
typedef enum _nxp_iot_AgentClaimStatus_ClaimStatus {
    nxp_iot_AgentClaimStatus_ClaimStatus_UNKNOWN = 0,
    /* The device was successfully claimed. */
    nxp_iot_AgentClaimStatus_ClaimStatus_SUCCESS = 1,
    /* The claim code is unknown or the UID of the device is not in the system. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_NOT_FOUND = 16,
    /* The claim code belongs to a device group that does not match the product
 type of the device. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_WRONG_PRODUCT_TYPE = 17,
    /* The claim code is known but has been revoked and therefore is not usable. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_CODE_REVOKED = 19,
    /* The claim code is no longer usable as it has reached the usage limit. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_CODE_LIMIT_REACHED = 20,
    /* This device has been claimed with this claim code already. Claiming it
 another time is not allowed. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_CODE_REUSE_PROHIBITED = 21,
    /* The claim code is not readable. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_CODE_READ = 22,
    /* The claim code on the secure subsystem has invalid policies, either they are too
 strict (EdgeLock 2GO cloud service is not able to read the claim code) or too
 loose (anybody can read the claim code and hence it has to be considered leaked). */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_CODE_POLICIES = 23,
    /* The claim code on the secure subsystem has an invalid object type. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_CODE_TYPE = 24,
    /* The claim code on the secure subsystem has an invalid format and failed validation. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_CODE_FORMAT = 25,
    /* The claim code could not be deleted. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_CODE_DELETE = 26,
    /* One ore more claim code errors happened. More details can be found
 in the details messages. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_CLAIM_FAILED = 64,
    /* An internal error occurred on the EdgeLock 2GO cloud service. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_INTERNAL = 80,
    /* A timeout happened on the EdgeLock 2GO cloud service. */
    nxp_iot_AgentClaimStatus_ClaimStatus_ERR_TIMEOUT = 81
} nxp_iot_AgentClaimStatus_ClaimStatus;

/* By convention status codes < 0x10 indicate success,
 status codes >= 0x10 indicate errors. */
typedef enum _nxp_iot_AgentRtpStatus_RtpStatus {
    nxp_iot_AgentRtpStatus_RtpStatus_UNKNOWN = 0,
    /* Remote trust provisioning was successful. */
    nxp_iot_AgentRtpStatus_RtpStatus_SUCCESS = 1,
    /* The object remained unchanged. It has been provisioned before, no
 attempt to provision it again has been made. */
    nxp_iot_AgentRtpStatus_RtpStatus_SUCCESS_NO_CHANGE = 2,
    /* Reading the attributes of an already existing object failed. */
    nxp_iot_AgentRtpStatus_RtpStatus_ERR_OBJECT_ATTRIBUTES_READ_FAILED = 16,
    /* Deletion of an existing object failed. */
    nxp_iot_AgentRtpStatus_RtpStatus_ERR_OBJECT_DELETE_FAILED = 17,
    /* Writing an object failed. */
    nxp_iot_AgentRtpStatus_RtpStatus_ERR_OBJECT_WRITE_FAILED = 18,
    /* The object is defective. A previous provisioning attempt failed, the object is marked
 as defective in the EdgeLock 2GO cloud service. No further attempt will be made until the
 object is reconfigured. */
    nxp_iot_AgentRtpStatus_RtpStatus_ERR_DEFECTIVE = 19,
    /* Installation of EC curve failed. */
    nxp_iot_AgentRtpStatus_RtpStatus_ERR_CURVE_INSTALLATION_FAILED = 20,
    /* Provisioning of one or more objects failed. Details can be found in
 the details messages. */
    nxp_iot_AgentRtpStatus_RtpStatus_ERR_RTP_FAILED = 64,
    /* An internal error occurred on the EdgeLock 2GO cloud service. */
    nxp_iot_AgentRtpStatus_RtpStatus_ERR_INTERNAL = 80,
    /* A timeout happened on the EdgeLock 2GO cloud service. */
    nxp_iot_AgentRtpStatus_RtpStatus_ERR_TIMEOUT = 81
} nxp_iot_AgentRtpStatus_RtpStatus;

/* By convention status codes < 0x10 indicate success,
 status codes >= 0x10 indicate errors. */
typedef enum _nxp_iot_AgentCspStatus_CspStatus {
    nxp_iot_AgentCspStatus_CspStatus_UNKNOWN = 0,
    /* The service was successfully provisioned (or no change to the provisioning was required). */
    nxp_iot_AgentCspStatus_CspStatus_SUCCESS = 1,
    /* The service remained unchanged. */
    nxp_iot_AgentCspStatus_CspStatus_SUCCESS_NO_CHANGE = 2,
    /* The service was successfully revoked. */
    nxp_iot_AgentCspStatus_CspStatus_SUCCESS_REVOKED = 3,
    /* The key slot for the key of a service is occupied and can not be re-used. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_KEY_SLOT_OCCUPIED = 16,
    /* Generation of a key required for cloud service provisioning failed. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_KEY_GENERATION_FAILED = 17,
    /* Read out of the public key (in order to certify it) failed. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_KEY_READOUT_FAILED = 18,
    /* Reading memory from a datastore failed. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_MEMORY_READ_FAILED = 19,
    /* Allocation of memory for writing to a datastore failed. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_MEMORY_ALLOCATION_FAILED = 20,
    /* Writing to a datastore failed. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_SERVICE_DESCRIPTOR_WRITE_FAILED = 21,
    /* Committing data to a datastore failed. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_MEMORY_COMMIT_FAILED = 23,
    /* The service is defective. A previous provisioning attempt failed, the service is marked
 as defective in the EdgeLock 2GO cloud service. No further attempt will be made until the
 service is reconfigured. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_DEFECTIVE = 22,
    /* One or more services failed to provision. Details can be found in
 the details messages. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_CSP_FAILED = 64,
    /* An internal error occurred on the EdgeLock 2GO cloud service. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_INTERNAL = 80,
    /* A timeout happened on the EdgeLock 2GO cloud service. */
    nxp_iot_AgentCspStatus_CspStatus_ERR_TIMEOUT = 81
} nxp_iot_AgentCspStatus_CspStatus;

/* By convention status codes < 0x10 indicate success,
 status codes >= 0x10 indicate errors. */
typedef enum _nxp_iot_UpdateStatusReport_UpdateStatus {
    nxp_iot_UpdateStatusReport_UpdateStatus_UNKNOWN = 0,
    /* Update was successful. */
    nxp_iot_UpdateStatusReport_UpdateStatus_SUCCESS = 1,
    /* The response is malformed and cannot be decoded as protobuf message. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_ENCODING = 16,
    /* The response is not expected according to the protocol. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_PROTOCOL = 17,
    /* Reading memory failed. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_MEMORY_READ = 18,
    /* Writing to memory failed. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_MEMORY_WRITE = 19,
    /* Communication to a secure subsystem failed. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_SSS_COMMUNICATION = 20,
    /* The version of a secure subsystem is not supported. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_SSS_VERSION = 21,
    /* Unable to establish a secure channel to the secure subsystem. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_SSS_SECURE_CHANNEL = 22,
    /* The endpoint configuration of the EdgeLock 2 GO agent is invalid. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_CONFIGURATION = 32,
    /* There are more than one datastore endpoints registered for cloud service provisioning. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_CONFIGURATION_TOO_MANY_DATASTORES = 33,
    /* There are more than one datastore endpoints registered for cloud service provisioning. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_CONFIGURATION_TOO_MANY_KEYSTORES = 34,
    /* The TLS handshake was OK, but no Server Name Indication (SNI) was used. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_CONFIGURATION_SNI_MISSING = 50,
    /* The Server Name Indication sent during TLS handshake does not contain a valid hostname. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_CONFIGURATION_SNI_INVALID = 51,
    /* The connection quota has been exceeded. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_CONNECTION_QUOTA_EXCEEDED = 52,
    /* The device is not part of any device-group. While this means it is a genuine device,
 perhaps it has not (yet) been whitelisted or it has been removed from all groups. It is
 currently not managed by EdgeLock 2GO cloud service. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_DEVICE_NOT_WHITELISTED = 53,
    /* Errors happened in one or more of the requested services.
 Please check in claimStatus, rtpStatus, ... for more details. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_UPDATE_FAILED = 64,
    /* An internal error happened on the EdgeLock 2GO cloud service. Please report
 a short description on what caused the issue and the correlationId that was
 sent as to part of the error notification to edgelock2go.support@nxp.com. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_INTERNAL = 80,
    /* A timeout happened on the EdgeLock 2GO cloud service. */
    nxp_iot_UpdateStatusReport_UpdateStatus_ERR_TIMEOUT = 81
} nxp_iot_UpdateStatusReport_UpdateStatus;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) nxp_iot_EndpointInformation_additionalData_t;
typedef PB_BYTES_ARRAY_T(64) nxp_iot_EndpointInformation_configurationState_t;
typedef struct _nxp_iot_EndpointInformation {
    bool has_type;
    nxp_iot_EndpointType type;
    /* Theoretically there can be multiple endpoints of the same type registered with one EdgeLock
 2GO agent. In order to distinguish them, they need to get an endpoint identifier. Every
 endpoint needs to have a unique identifier (unique on that device/EdgeLock 2GO agent
 instance). */
    bool has_endpointId;
    uint32_t endpointId;
    /* Convey information about the version of a particular endpoint implementation. Note: a version
 is always defined as W.X.Y.Z, where all letters represent a number from 0-255 with W|X being
 the major version, Y the minor version, Z, the patch version. */
    bool has_version;
    uint32_t version;
    /* Used to deploy state information from an endpoint to the EdgeLock 2GO cloud service.
 Interpretation of the value is specific to the particular endpoint driver. */
    bool has_state;
    int32_t state;
    /* Additional meta-data from an endpoint to the EdgeLock 2GO cloud service. Interpretation of
 the value is specific to the particular endpoint driver. */
    bool has_additionalData;
    nxp_iot_EndpointInformation_additionalData_t additionalData;
    /* A configuration state of an endpoint - allows for optimization of update detection of an
 Interpretation of the value is specific to the particular endpoint driver. */
    bool has_configurationState;
    nxp_iot_EndpointInformation_configurationState_t configurationState;
} nxp_iot_EndpointInformation;

typedef struct _nxp_iot_AgentHelloRequest {
    /* Convey information about the version of the EdgeLock 2GO cloud service implementation (mainly
 for informative purpouse). Note: a version is always defined as W.X.Y.Z, where all letters
 represent a number from 0-255 with W|X being the major version, Y the minor version, Z, the
 patch version. */
    bool has_version;
    uint32_t version;
    /* Some state information about the device. Most importantly this is used to force an in-depth
 check on the endpoint states by the EdgeLock 2GO cloud service.

 No state handling is implemented in the EdgeLock 2GO cloud service for now. */
    bool has_state;
    nxp_iot_AgentHelloRequest_DeviceState state;
    /* The maximum size of the message that the server can receive from the client. */
    bool has_communicationBufferSize;
    int32_t communicationBufferSize;
} nxp_iot_AgentHelloRequest;

typedef struct _nxp_iot_AgentHelloResponse {
    /* The version of the EdgeLock 2GO agent that is running. Note: a version is always defined as
 W.X.Y.Z, where all letters represent a number from 0-255 with W|X being the major version, Y
 the minor version, Z, the patch version. */
    bool has_version;
    uint32_t version;
    /* The size of the buffer used for assembling a response from the client to the server (a.k.a.
 the maximal size that the responses of ALL endpoint requests (accumulated) can take).

 The default value given here is a fallback. The real situation does depend on the system
 configuration (e.g., it is not clever/possible to chain response APDUs, the size needs to be
 adapted for that on the client side). */
    bool has_communicationBufferSizeResponses;
    int32_t communicationBufferSizeResponses;
    /* The size of the buffer used for decoding requests from the server. */
    bool has_communicationBufferSizeRequests;
    int32_t communicationBufferSizeRequests;
    /* The layout of the service descriptor structure that is understood by the agent. Deprecated -
 replaced by serviceDescriptorVersion in AgentAdditionalData. */
    bool has_serviceDescriptorVersion;
    nxp_iot_ServiceDescriptorVersion serviceDescriptorVersion;
    /* If this is enabled, the EdgeLock 2GO cloud service combines multiple requests in one message
 to the EdgeLock 2GO agent. 

 It does pre-calculate the max required space for a response. Based on this calculation it
 knows how many responses fit into the response buffer and will send an according number of
 requests in a single message. */
    bool has_useMultipleRequestsPerMessage;
    bool useMultipleRequestsPerMessage;
    /* Information about all endpoints that are available. */
    pb_size_t endpoints_count;
    nxp_iot_EndpointInformation endpoints[5];
} nxp_iot_AgentHelloResponse;

typedef struct _nxp_iot_AgentAdditionalData {
    /* The layout of the service descriptor structure that is understood by the agent. */
    bool has_serviceDescriptorVersion;
    nxp_iot_ServiceDescriptorVersion serviceDescriptorVersion;
    /* Shall the server send a message containing a CRL. */
    bool has_requestCrl;
    bool requestCrl;
    /* Shall the server include metadata with requests. This allows to get a
 detailed picture on the individual steps taken by the orchestration logic
 and can aid in debugging/logging. */
    bool has_sendRequestMetadata;
    bool sendRequestMetadata;
} nxp_iot_AgentAdditionalData;

typedef struct _nxp_iot_AgentClaimStatus {
    bool has_status;
    nxp_iot_AgentClaimStatus_ClaimStatus status;
    pb_size_t details_count;
    struct _nxp_iot_AgentClaimStatus_DetailedClaimStatus *details;
} nxp_iot_AgentClaimStatus;

typedef struct _nxp_iot_AgentClaimStatus_DetailedClaimStatus {
    bool has_status;
    nxp_iot_AgentClaimStatus_ClaimStatus status;
    bool has_endpointId;
    uint32_t endpointId;
} nxp_iot_AgentClaimStatus_DetailedClaimStatus;

typedef struct _nxp_iot_AgentRtpStatus {
    bool has_status;
    nxp_iot_AgentRtpStatus_RtpStatus status;
    pb_size_t details_count;
    struct _nxp_iot_AgentRtpStatus_RtpObjectStatus *details;
} nxp_iot_AgentRtpStatus;

typedef struct _nxp_iot_AgentRtpStatus_RtpObjectStatus {
    bool has_status;
    nxp_iot_AgentRtpStatus_RtpStatus status;
    bool has_endpointId;
    uint32_t endpointId;
    bool has_objectId;
    uint32_t objectId;
} nxp_iot_AgentRtpStatus_RtpObjectStatus;

typedef struct _nxp_iot_AgentCspStatus {
    bool has_status;
    nxp_iot_AgentCspStatus_CspStatus status;
    pb_size_t details_count;
    struct _nxp_iot_AgentCspStatus_CspServiceStatus *details;
} nxp_iot_AgentCspStatus;

typedef struct _nxp_iot_AgentCspStatus_CspServiceStatus {
    bool has_status;
    nxp_iot_AgentCspStatus_CspStatus status;
    bool has_endpointId;
    uint32_t endpointId;
    bool has_serviceId;
    uint64_t serviceId;
} nxp_iot_AgentCspStatus_CspServiceStatus;

typedef struct _nxp_iot_UpdateStatusReport {
    bool has_status;
    nxp_iot_UpdateStatusReport_UpdateStatus status;
    bool has_claimStatus;
    nxp_iot_AgentClaimStatus claimStatus;
    bool has_rtpStatus;
    nxp_iot_AgentRtpStatus rtpStatus;
    bool has_cspStatus;
    nxp_iot_AgentCspStatus cspStatus;
    /* A unique identifier for this device update attempt. in case of a failure, this eases debugging
 by allowing to identify all log messages that belong to this attempt in
 the EdgeLock 2GO cloud service. */
    bool has_correlationId;
    char correlationId[37];
} nxp_iot_UpdateStatusReport;

typedef struct _nxp_iot_AgentGoodbyeRequest {
    bool has_status;
    nxp_iot_UpdateStatusReport status;
} nxp_iot_AgentGoodbyeRequest;

typedef struct _nxp_iot_AgentCrlRequest {
    pb_bytes_array_t *crl;
} nxp_iot_AgentCrlRequest;

typedef struct _nxp_iot_AgentCrlResponse {
    bool has_error;
    uint32_t error;
} nxp_iot_AgentCrlResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _nxp_iot_ServiceDescriptorVersion_MIN nxp_iot_ServiceDescriptorVersion_C_STRUCTURE_01
#define _nxp_iot_ServiceDescriptorVersion_MAX nxp_iot_ServiceDescriptorVersion_PROTOBUF
#define _nxp_iot_ServiceDescriptorVersion_ARRAYSIZE ((nxp_iot_ServiceDescriptorVersion)(nxp_iot_ServiceDescriptorVersion_PROTOBUF+1))

#define _nxp_iot_AgentHelloRequest_DeviceState_MIN nxp_iot_AgentHelloRequest_DeviceState_OK
#define _nxp_iot_AgentHelloRequest_DeviceState_MAX nxp_iot_AgentHelloRequest_DeviceState_FORCE_UPDATE
#define _nxp_iot_AgentHelloRequest_DeviceState_ARRAYSIZE ((nxp_iot_AgentHelloRequest_DeviceState)(nxp_iot_AgentHelloRequest_DeviceState_FORCE_UPDATE+1))

#define _nxp_iot_AgentClaimStatus_ClaimStatus_MIN nxp_iot_AgentClaimStatus_ClaimStatus_UNKNOWN
#define _nxp_iot_AgentClaimStatus_ClaimStatus_MAX nxp_iot_AgentClaimStatus_ClaimStatus_ERR_TIMEOUT
#define _nxp_iot_AgentClaimStatus_ClaimStatus_ARRAYSIZE ((nxp_iot_AgentClaimStatus_ClaimStatus)(nxp_iot_AgentClaimStatus_ClaimStatus_ERR_TIMEOUT+1))

#define _nxp_iot_AgentRtpStatus_RtpStatus_MIN nxp_iot_AgentRtpStatus_RtpStatus_UNKNOWN
#define _nxp_iot_AgentRtpStatus_RtpStatus_MAX nxp_iot_AgentRtpStatus_RtpStatus_ERR_TIMEOUT
#define _nxp_iot_AgentRtpStatus_RtpStatus_ARRAYSIZE ((nxp_iot_AgentRtpStatus_RtpStatus)(nxp_iot_AgentRtpStatus_RtpStatus_ERR_TIMEOUT+1))

#define _nxp_iot_AgentCspStatus_CspStatus_MIN nxp_iot_AgentCspStatus_CspStatus_UNKNOWN
#define _nxp_iot_AgentCspStatus_CspStatus_MAX nxp_iot_AgentCspStatus_CspStatus_ERR_TIMEOUT
#define _nxp_iot_AgentCspStatus_CspStatus_ARRAYSIZE ((nxp_iot_AgentCspStatus_CspStatus)(nxp_iot_AgentCspStatus_CspStatus_ERR_TIMEOUT+1))

#define _nxp_iot_UpdateStatusReport_UpdateStatus_MIN nxp_iot_UpdateStatusReport_UpdateStatus_UNKNOWN
#define _nxp_iot_UpdateStatusReport_UpdateStatus_MAX nxp_iot_UpdateStatusReport_UpdateStatus_ERR_TIMEOUT
#define _nxp_iot_UpdateStatusReport_UpdateStatus_ARRAYSIZE ((nxp_iot_UpdateStatusReport_UpdateStatus)(nxp_iot_UpdateStatusReport_UpdateStatus_ERR_TIMEOUT+1))

#define nxp_iot_EndpointInformation_type_ENUMTYPE nxp_iot_EndpointType

#define nxp_iot_AgentHelloRequest_state_ENUMTYPE nxp_iot_AgentHelloRequest_DeviceState

#define nxp_iot_AgentHelloResponse_serviceDescriptorVersion_ENUMTYPE nxp_iot_ServiceDescriptorVersion

#define nxp_iot_AgentAdditionalData_serviceDescriptorVersion_ENUMTYPE nxp_iot_ServiceDescriptorVersion

#define nxp_iot_AgentClaimStatus_status_ENUMTYPE nxp_iot_AgentClaimStatus_ClaimStatus

#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_status_ENUMTYPE nxp_iot_AgentClaimStatus_ClaimStatus

#define nxp_iot_AgentRtpStatus_status_ENUMTYPE nxp_iot_AgentRtpStatus_RtpStatus

#define nxp_iot_AgentRtpStatus_RtpObjectStatus_status_ENUMTYPE nxp_iot_AgentRtpStatus_RtpStatus

#define nxp_iot_AgentCspStatus_status_ENUMTYPE nxp_iot_AgentCspStatus_CspStatus

#define nxp_iot_AgentCspStatus_CspServiceStatus_status_ENUMTYPE nxp_iot_AgentCspStatus_CspStatus

#define nxp_iot_UpdateStatusReport_status_ENUMTYPE nxp_iot_UpdateStatusReport_UpdateStatus





/* Initializer values for message structs */
#define nxp_iot_EndpointInformation_init_default {false, _nxp_iot_EndpointType_MIN, false, 0, false, 0, false, 0, false, {0, {0}}, false, {0, {0}}}
#define nxp_iot_AgentHelloRequest_init_default   {false, 0, false, _nxp_iot_AgentHelloRequest_DeviceState_MIN, false, 0}
#define nxp_iot_AgentHelloResponse_init_default  {false, 0, false, 1024, false, 1024, false, nxp_iot_ServiceDescriptorVersion_PROTOBUF, false, false, 0, {nxp_iot_EndpointInformation_init_default, nxp_iot_EndpointInformation_init_default, nxp_iot_EndpointInformation_init_default, nxp_iot_EndpointInformation_init_default, nxp_iot_EndpointInformation_init_default}}
#define nxp_iot_AgentAdditionalData_init_default {false, nxp_iot_ServiceDescriptorVersion_PROTOBUF, false, 0, false, 0}
#define nxp_iot_AgentClaimStatus_init_default    {false, _nxp_iot_AgentClaimStatus_ClaimStatus_MIN, 0, NULL}
#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_init_default {false, _nxp_iot_AgentClaimStatus_ClaimStatus_MIN, false, 0}
#define nxp_iot_AgentRtpStatus_init_default      {false, _nxp_iot_AgentRtpStatus_RtpStatus_MIN, 0, NULL}
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_init_default {false, _nxp_iot_AgentRtpStatus_RtpStatus_MIN, false, 0, false, 0}
#define nxp_iot_AgentCspStatus_init_default      {false, _nxp_iot_AgentCspStatus_CspStatus_MIN, 0, NULL}
#define nxp_iot_AgentCspStatus_CspServiceStatus_init_default {false, _nxp_iot_AgentCspStatus_CspStatus_MIN, false, 0, false, 0}
#define nxp_iot_UpdateStatusReport_init_default  {false, _nxp_iot_UpdateStatusReport_UpdateStatus_MIN, false, nxp_iot_AgentClaimStatus_init_default, false, nxp_iot_AgentRtpStatus_init_default, false, nxp_iot_AgentCspStatus_init_default, false, ""}
#define nxp_iot_AgentGoodbyeRequest_init_default {false, nxp_iot_UpdateStatusReport_init_default}
#define nxp_iot_AgentCrlRequest_init_default     {NULL}
#define nxp_iot_AgentCrlResponse_init_default    {false, 0}
#define nxp_iot_EndpointInformation_init_zero    {false, _nxp_iot_EndpointType_MIN, false, 0, false, 0, false, 0, false, {0, {0}}, false, {0, {0}}}
#define nxp_iot_AgentHelloRequest_init_zero      {false, 0, false, _nxp_iot_AgentHelloRequest_DeviceState_MIN, false, 0}
#define nxp_iot_AgentHelloResponse_init_zero     {false, 0, false, 0, false, 0, false, _nxp_iot_ServiceDescriptorVersion_MIN, false, 0, 0, {nxp_iot_EndpointInformation_init_zero, nxp_iot_EndpointInformation_init_zero, nxp_iot_EndpointInformation_init_zero, nxp_iot_EndpointInformation_init_zero, nxp_iot_EndpointInformation_init_zero}}
#define nxp_iot_AgentAdditionalData_init_zero    {false, _nxp_iot_ServiceDescriptorVersion_MIN, false, 0, false, 0}
#define nxp_iot_AgentClaimStatus_init_zero       {false, _nxp_iot_AgentClaimStatus_ClaimStatus_MIN, 0, NULL}
#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_init_zero {false, _nxp_iot_AgentClaimStatus_ClaimStatus_MIN, false, 0}
#define nxp_iot_AgentRtpStatus_init_zero         {false, _nxp_iot_AgentRtpStatus_RtpStatus_MIN, 0, NULL}
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_init_zero {false, _nxp_iot_AgentRtpStatus_RtpStatus_MIN, false, 0, false, 0}
#define nxp_iot_AgentCspStatus_init_zero         {false, _nxp_iot_AgentCspStatus_CspStatus_MIN, 0, NULL}
#define nxp_iot_AgentCspStatus_CspServiceStatus_init_zero {false, _nxp_iot_AgentCspStatus_CspStatus_MIN, false, 0, false, 0}
#define nxp_iot_UpdateStatusReport_init_zero     {false, _nxp_iot_UpdateStatusReport_UpdateStatus_MIN, false, nxp_iot_AgentClaimStatus_init_zero, false, nxp_iot_AgentRtpStatus_init_zero, false, nxp_iot_AgentCspStatus_init_zero, false, ""}
#define nxp_iot_AgentGoodbyeRequest_init_zero    {false, nxp_iot_UpdateStatusReport_init_zero}
#define nxp_iot_AgentCrlRequest_init_zero        {NULL}
#define nxp_iot_AgentCrlResponse_init_zero       {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_EndpointInformation_type_tag     1
#define nxp_iot_EndpointInformation_endpointId_tag 2
#define nxp_iot_EndpointInformation_version_tag  3
#define nxp_iot_EndpointInformation_state_tag    4
#define nxp_iot_EndpointInformation_additionalData_tag 5
#define nxp_iot_EndpointInformation_configurationState_tag 6
#define nxp_iot_AgentHelloRequest_version_tag    1
#define nxp_iot_AgentHelloRequest_state_tag      2
#define nxp_iot_AgentHelloRequest_communicationBufferSize_tag 20
#define nxp_iot_AgentHelloResponse_version_tag   1
#define nxp_iot_AgentHelloResponse_communicationBufferSizeResponses_tag 2
#define nxp_iot_AgentHelloResponse_communicationBufferSizeRequests_tag 3
#define nxp_iot_AgentHelloResponse_serviceDescriptorVersion_tag 4
#define nxp_iot_AgentHelloResponse_useMultipleRequestsPerMessage_tag 5
#define nxp_iot_AgentHelloResponse_endpoints_tag 10
#define nxp_iot_AgentAdditionalData_serviceDescriptorVersion_tag 1
#define nxp_iot_AgentAdditionalData_requestCrl_tag 2
#define nxp_iot_AgentAdditionalData_sendRequestMetadata_tag 3
#define nxp_iot_AgentClaimStatus_status_tag      1
#define nxp_iot_AgentClaimStatus_details_tag     2
#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_status_tag 1
#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_endpointId_tag 2
#define nxp_iot_AgentRtpStatus_status_tag        1
#define nxp_iot_AgentRtpStatus_details_tag       2
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_status_tag 1
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_endpointId_tag 2
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_objectId_tag 3
#define nxp_iot_AgentCspStatus_status_tag        1
#define nxp_iot_AgentCspStatus_details_tag       2
#define nxp_iot_AgentCspStatus_CspServiceStatus_status_tag 1
#define nxp_iot_AgentCspStatus_CspServiceStatus_endpointId_tag 2
#define nxp_iot_AgentCspStatus_CspServiceStatus_serviceId_tag 3
#define nxp_iot_UpdateStatusReport_status_tag    1
#define nxp_iot_UpdateStatusReport_claimStatus_tag 2
#define nxp_iot_UpdateStatusReport_rtpStatus_tag 3
#define nxp_iot_UpdateStatusReport_cspStatus_tag 4
#define nxp_iot_UpdateStatusReport_correlationId_tag 5
#define nxp_iot_AgentGoodbyeRequest_status_tag   1
#define nxp_iot_AgentCrlRequest_crl_tag          1
#define nxp_iot_AgentCrlResponse_error_tag       1

/* Struct field encoding specification for nanopb */
#define nxp_iot_EndpointInformation_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   endpointId,        2) \
X(a, STATIC,   OPTIONAL, FIXED32,  version,           3) \
X(a, STATIC,   OPTIONAL, INT32,    state,             4) \
X(a, STATIC,   OPTIONAL, BYTES,    additionalData,    5) \
X(a, STATIC,   OPTIONAL, BYTES,    configurationState,   6)
#define nxp_iot_EndpointInformation_CALLBACK NULL
#define nxp_iot_EndpointInformation_DEFAULT NULL

#define nxp_iot_AgentHelloRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED32,  version,           1) \
X(a, STATIC,   OPTIONAL, UENUM,    state,             2) \
X(a, STATIC,   OPTIONAL, INT32,    communicationBufferSize,  20)
#define nxp_iot_AgentHelloRequest_CALLBACK NULL
#define nxp_iot_AgentHelloRequest_DEFAULT NULL

#define nxp_iot_AgentHelloResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED32,  version,           1) \
X(a, STATIC,   OPTIONAL, INT32,    communicationBufferSizeResponses,   2) \
X(a, STATIC,   OPTIONAL, INT32,    communicationBufferSizeRequests,   3) \
X(a, STATIC,   OPTIONAL, UENUM,    serviceDescriptorVersion,   4) \
X(a, STATIC,   OPTIONAL, BOOL,     useMultipleRequestsPerMessage,   5) \
X(a, STATIC,   REPEATED, MESSAGE,  endpoints,        10)
#define nxp_iot_AgentHelloResponse_CALLBACK NULL
#define nxp_iot_AgentHelloResponse_DEFAULT (const pb_byte_t*)"\x10\x80\x08\x18\x80\x08\x20\x0a\x28\x00\x00"
#define nxp_iot_AgentHelloResponse_endpoints_MSGTYPE nxp_iot_EndpointInformation

#define nxp_iot_AgentAdditionalData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    serviceDescriptorVersion,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     requestCrl,        2) \
X(a, STATIC,   OPTIONAL, BOOL,     sendRequestMetadata,   3)
#define nxp_iot_AgentAdditionalData_CALLBACK NULL
#define nxp_iot_AgentAdditionalData_DEFAULT (const pb_byte_t*)"\x08\x0a\x00"

#define nxp_iot_AgentClaimStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1) \
X(a, POINTER,  REPEATED, MESSAGE,  details,           2)
#define nxp_iot_AgentClaimStatus_CALLBACK NULL
#define nxp_iot_AgentClaimStatus_DEFAULT NULL
#define nxp_iot_AgentClaimStatus_details_MSGTYPE nxp_iot_AgentClaimStatus_DetailedClaimStatus

#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   endpointId,        2)
#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_CALLBACK NULL
#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_DEFAULT NULL

#define nxp_iot_AgentRtpStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1) \
X(a, POINTER,  REPEATED, MESSAGE,  details,           2)
#define nxp_iot_AgentRtpStatus_CALLBACK NULL
#define nxp_iot_AgentRtpStatus_DEFAULT NULL
#define nxp_iot_AgentRtpStatus_details_MSGTYPE nxp_iot_AgentRtpStatus_RtpObjectStatus

#define nxp_iot_AgentRtpStatus_RtpObjectStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   endpointId,        2) \
X(a, STATIC,   OPTIONAL, UINT32,   objectId,          3)
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_CALLBACK NULL
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_DEFAULT NULL

#define nxp_iot_AgentCspStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1) \
X(a, POINTER,  REPEATED, MESSAGE,  details,           2)
#define nxp_iot_AgentCspStatus_CALLBACK NULL
#define nxp_iot_AgentCspStatus_DEFAULT NULL
#define nxp_iot_AgentCspStatus_details_MSGTYPE nxp_iot_AgentCspStatus_CspServiceStatus

#define nxp_iot_AgentCspStatus_CspServiceStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   endpointId,        2) \
X(a, STATIC,   OPTIONAL, UINT64,   serviceId,         3)
#define nxp_iot_AgentCspStatus_CspServiceStatus_CALLBACK NULL
#define nxp_iot_AgentCspStatus_CspServiceStatus_DEFAULT NULL

#define nxp_iot_UpdateStatusReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  claimStatus,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rtpStatus,         3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cspStatus,         4) \
X(a, STATIC,   OPTIONAL, STRING,   correlationId,     5)
#define nxp_iot_UpdateStatusReport_CALLBACK NULL
#define nxp_iot_UpdateStatusReport_DEFAULT NULL
#define nxp_iot_UpdateStatusReport_claimStatus_MSGTYPE nxp_iot_AgentClaimStatus
#define nxp_iot_UpdateStatusReport_rtpStatus_MSGTYPE nxp_iot_AgentRtpStatus
#define nxp_iot_UpdateStatusReport_cspStatus_MSGTYPE nxp_iot_AgentCspStatus

#define nxp_iot_AgentGoodbyeRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1)
#define nxp_iot_AgentGoodbyeRequest_CALLBACK NULL
#define nxp_iot_AgentGoodbyeRequest_DEFAULT NULL
#define nxp_iot_AgentGoodbyeRequest_status_MSGTYPE nxp_iot_UpdateStatusReport

#define nxp_iot_AgentCrlRequest_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, BYTES,    crl,               1)
#define nxp_iot_AgentCrlRequest_CALLBACK NULL
#define nxp_iot_AgentCrlRequest_DEFAULT NULL

#define nxp_iot_AgentCrlResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED32,  error,             1)
#define nxp_iot_AgentCrlResponse_CALLBACK NULL
#define nxp_iot_AgentCrlResponse_DEFAULT NULL

extern const pb_msgdesc_t nxp_iot_EndpointInformation_msg;
extern const pb_msgdesc_t nxp_iot_AgentHelloRequest_msg;
extern const pb_msgdesc_t nxp_iot_AgentHelloResponse_msg;
extern const pb_msgdesc_t nxp_iot_AgentAdditionalData_msg;
extern const pb_msgdesc_t nxp_iot_AgentClaimStatus_msg;
extern const pb_msgdesc_t nxp_iot_AgentClaimStatus_DetailedClaimStatus_msg;
extern const pb_msgdesc_t nxp_iot_AgentRtpStatus_msg;
extern const pb_msgdesc_t nxp_iot_AgentRtpStatus_RtpObjectStatus_msg;
extern const pb_msgdesc_t nxp_iot_AgentCspStatus_msg;
extern const pb_msgdesc_t nxp_iot_AgentCspStatus_CspServiceStatus_msg;
extern const pb_msgdesc_t nxp_iot_UpdateStatusReport_msg;
extern const pb_msgdesc_t nxp_iot_AgentGoodbyeRequest_msg;
extern const pb_msgdesc_t nxp_iot_AgentCrlRequest_msg;
extern const pb_msgdesc_t nxp_iot_AgentCrlResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_EndpointInformation_fields &nxp_iot_EndpointInformation_msg
#define nxp_iot_AgentHelloRequest_fields &nxp_iot_AgentHelloRequest_msg
#define nxp_iot_AgentHelloResponse_fields &nxp_iot_AgentHelloResponse_msg
#define nxp_iot_AgentAdditionalData_fields &nxp_iot_AgentAdditionalData_msg
#define nxp_iot_AgentClaimStatus_fields &nxp_iot_AgentClaimStatus_msg
#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_fields &nxp_iot_AgentClaimStatus_DetailedClaimStatus_msg
#define nxp_iot_AgentRtpStatus_fields &nxp_iot_AgentRtpStatus_msg
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_fields &nxp_iot_AgentRtpStatus_RtpObjectStatus_msg
#define nxp_iot_AgentCspStatus_fields &nxp_iot_AgentCspStatus_msg
#define nxp_iot_AgentCspStatus_CspServiceStatus_fields &nxp_iot_AgentCspStatus_CspServiceStatus_msg
#define nxp_iot_UpdateStatusReport_fields &nxp_iot_UpdateStatusReport_msg
#define nxp_iot_AgentGoodbyeRequest_fields &nxp_iot_AgentGoodbyeRequest_msg
#define nxp_iot_AgentCrlRequest_fields &nxp_iot_AgentCrlRequest_msg
#define nxp_iot_AgentCrlResponse_fields &nxp_iot_AgentCrlResponse_msg

/* Maximum encoded size of messages (where known) */
/* nxp_iot_AgentClaimStatus_size depends on runtime parameters */
/* nxp_iot_AgentRtpStatus_size depends on runtime parameters */
/* nxp_iot_AgentCspStatus_size depends on runtime parameters */
/* nxp_iot_UpdateStatusReport_size depends on runtime parameters */
/* nxp_iot_AgentGoodbyeRequest_size depends on runtime parameters */
/* nxp_iot_AgentCrlRequest_size depends on runtime parameters */
#define NXP_IOT_AGENT_PB_H_MAX_SIZE              nxp_iot_AgentHelloResponse_size
#define nxp_iot_AgentAdditionalData_size         6
#define nxp_iot_AgentClaimStatus_DetailedClaimStatus_size 8
#define nxp_iot_AgentCrlResponse_size            5
#define nxp_iot_AgentCspStatus_CspServiceStatus_size 19
#define nxp_iot_AgentHelloRequest_size           19
#define nxp_iot_AgentHelloResponse_size          826
#define nxp_iot_AgentRtpStatus_RtpObjectStatus_size 14
#define nxp_iot_EndpointInformation_size         156

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
