/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_APDU_PB_H_INCLUDED
#define PB_NXP_IOT_APDU_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* doc:apdu-reqeuest:start */
typedef struct _nxp_iot_ApduRequest {
    /* Array of bytes to be sent to the SE */
    pb_callback_t message;
    /* What response is expected from the SE for this APDU?

 If this field is skipped from protobuf, then,
 only 0x9000 is expected from the SE

 There are potentially multiple distinct values
 are expected the from the SE, then this
 can be an array of those values.

      e.g.    expectation: [ 0x9000, 0x6A82 ]

 For complex schems where a every big range/mask
 is expected, e.g. 6AXX, 6DXX then the upper
 16 bits are treated as mask.

      e.g.    expectation: [ 0x00FF6A00, 0x00FF6D00 ]

 This field is unused by EdgeLock 2GO cloud service. */
    pb_callback_t expectation;
} nxp_iot_ApduRequest;

/* Response from the SE to host */
typedef struct _nxp_iot_ApduResponse {
    /* Byte array */
    pb_callback_t message;
} nxp_iot_ApduResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define nxp_iot_ApduRequest_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define nxp_iot_ApduResponse_init_default        {{{NULL}, NULL}}
#define nxp_iot_ApduRequest_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define nxp_iot_ApduResponse_init_zero           {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_ApduRequest_message_tag          100
#define nxp_iot_ApduRequest_expectation_tag      101
#define nxp_iot_ApduResponse_message_tag         100

/* Struct field encoding specification for nanopb */
#define nxp_iot_ApduRequest_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    message,         100) \
X(a, CALLBACK, REPEATED, UINT32,   expectation,     101)
#define nxp_iot_ApduRequest_CALLBACK pb_default_field_callback
#define nxp_iot_ApduRequest_DEFAULT NULL

#define nxp_iot_ApduResponse_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    message,         100)
#define nxp_iot_ApduResponse_CALLBACK pb_default_field_callback
#define nxp_iot_ApduResponse_DEFAULT NULL

extern const pb_msgdesc_t nxp_iot_ApduRequest_msg;
extern const pb_msgdesc_t nxp_iot_ApduResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_ApduRequest_fields &nxp_iot_ApduRequest_msg
#define nxp_iot_ApduResponse_fields &nxp_iot_ApduResponse_msg

/* Maximum encoded size of messages (where known) */
/* nxp_iot_ApduRequest_size depends on runtime parameters */
/* nxp_iot_ApduResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
