/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_DATASTORE_PB_H_INCLUDED
#define PB_NXP_IOT_DATASTORE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _nxp_iot_DatastoreOperation {
    /* Before an update to a datastore, the EdgeLock 2GO cloud service requests the datastore to
 allocate the memory that is required. This operation also indicates the start of a
 transaction.

 A request containing an ALLOCATE operation does use the \p length field to indicate the total
 amount of memory required for the data to be written to the datastore. */
    nxp_iot_DatastoreOperation_ALLOCATE = 1,
    /* The EdgeLock 2GO cloud service might need to read data from a datastore to determine its
 current state.

 A request containing a READ operation does use the \p offset and \p length fields to indicate
 where to start and how many bytes to read from the datastore. */
    nxp_iot_DatastoreOperation_READ = 2,
    /* To fill the datastore with contents, the EdgeLock 2GO cloud service is using this operation.
 Note that several writes might be used to fill the datastore (depending on the buffer sizes
 for communication).

 A request containing a WRITE operation does use the \p offset and \p data fields of the
 message to indicate where in the datastore to start and what data to write. */
    nxp_iot_DatastoreOperation_WRITE = 3,
    /* If the datastore indicates that it supports transactions, after all necessary writes are
 done, the EdgeLock 2GO cloud service does indicate that with this operation. This is the
 indication to the datastore to invalidate old contents and from that point in time onwards
 use the data that was updated with transaction that is committed.

 A request containing a COMMIT operation does not use any message fields. */
    nxp_iot_DatastoreOperation_COMMIT = 4
} nxp_iot_DatastoreOperation;

typedef enum _nxp_iot_DatastoreStatus {
    nxp_iot_DatastoreStatus_OK = 1,
    nxp_iot_DatastoreStatus_ERROR = 2
} nxp_iot_DatastoreStatus;

typedef enum _nxp_iot_DatastoreIdentifiers {
    /* If a datastore has this ID, it will be used to store the information to connect to the
 EdgeLock 2GO cloud service itself. It will not be used to store other cloud service
 connection information unless it is the only datastore available. */
    nxp_iot_DatastoreIdentifiers_DATASTORE_EDGELOCK2GO_ID = 1879048192
} nxp_iot_DatastoreIdentifiers;

/* Struct definitions */
typedef struct _nxp_iot_DatastoreAdditionalData {
    /* Datastore writes might be done in chunks (using several WRITE operations). Since the
 connection to EdgeLock 2GO could be interrupted at any point in time, it could happen that
 some chunks of the datastore have been written already while others have not, resulting in an
 unusable datastore.

 To protect from that situation, a datastore can implement a simple transaction interface. In
 this case it can signal to use transactions to the EdgeLock 2GO cloud service with this
 field. This will make the EdgeLock 2GO cloud service indicate that all datastore writes that
 it needs to do to one datastore are complete with an additional commit operation. */
    bool has_supportsTransactions;
    bool supportsTransactions;
} nxp_iot_DatastoreAdditionalData;

typedef struct _nxp_iot_DatastoreRequest {
    bool has_operation;
    nxp_iot_DatastoreOperation operation;
    bool has_offset;
    int32_t offset;
    bool has_length;
    int32_t length;
    pb_callback_t data;
} nxp_iot_DatastoreRequest;

typedef struct _nxp_iot_DatastoreResponse {
    bool has_status;
    nxp_iot_DatastoreStatus status;
    bool has_length;
    int32_t length;
    pb_callback_t data;
} nxp_iot_DatastoreResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _nxp_iot_DatastoreOperation_MIN nxp_iot_DatastoreOperation_ALLOCATE
#define _nxp_iot_DatastoreOperation_MAX nxp_iot_DatastoreOperation_COMMIT
#define _nxp_iot_DatastoreOperation_ARRAYSIZE ((nxp_iot_DatastoreOperation)(nxp_iot_DatastoreOperation_COMMIT+1))

#define _nxp_iot_DatastoreStatus_MIN nxp_iot_DatastoreStatus_OK
#define _nxp_iot_DatastoreStatus_MAX nxp_iot_DatastoreStatus_ERROR
#define _nxp_iot_DatastoreStatus_ARRAYSIZE ((nxp_iot_DatastoreStatus)(nxp_iot_DatastoreStatus_ERROR+1))

#define _nxp_iot_DatastoreIdentifiers_MIN nxp_iot_DatastoreIdentifiers_DATASTORE_EDGELOCK2GO_ID
#define _nxp_iot_DatastoreIdentifiers_MAX nxp_iot_DatastoreIdentifiers_DATASTORE_EDGELOCK2GO_ID
#define _nxp_iot_DatastoreIdentifiers_ARRAYSIZE ((nxp_iot_DatastoreIdentifiers)(nxp_iot_DatastoreIdentifiers_DATASTORE_EDGELOCK2GO_ID+1))


#define nxp_iot_DatastoreRequest_operation_ENUMTYPE nxp_iot_DatastoreOperation

#define nxp_iot_DatastoreResponse_status_ENUMTYPE nxp_iot_DatastoreStatus


/* Initializer values for message structs */
#define nxp_iot_DatastoreAdditionalData_init_default {false, 0}
#define nxp_iot_DatastoreRequest_init_default    {false, _nxp_iot_DatastoreOperation_MIN, false, 0, false, 0, {{NULL}, NULL}}
#define nxp_iot_DatastoreResponse_init_default   {false, _nxp_iot_DatastoreStatus_MIN, false, 0, {{NULL}, NULL}}
#define nxp_iot_DatastoreAdditionalData_init_zero {false, 0}
#define nxp_iot_DatastoreRequest_init_zero       {false, _nxp_iot_DatastoreOperation_MIN, false, 0, false, 0, {{NULL}, NULL}}
#define nxp_iot_DatastoreResponse_init_zero      {false, _nxp_iot_DatastoreStatus_MIN, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_DatastoreAdditionalData_supportsTransactions_tag 1
#define nxp_iot_DatastoreRequest_operation_tag   1
#define nxp_iot_DatastoreRequest_offset_tag      2
#define nxp_iot_DatastoreRequest_length_tag      3
#define nxp_iot_DatastoreRequest_data_tag        10
#define nxp_iot_DatastoreResponse_status_tag     1
#define nxp_iot_DatastoreResponse_length_tag     2
#define nxp_iot_DatastoreResponse_data_tag       10

/* Struct field encoding specification for nanopb */
#define nxp_iot_DatastoreAdditionalData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     supportsTransactions,   1)
#define nxp_iot_DatastoreAdditionalData_CALLBACK NULL
#define nxp_iot_DatastoreAdditionalData_DEFAULT NULL

#define nxp_iot_DatastoreRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    operation,         1) \
X(a, STATIC,   OPTIONAL, INT32,    offset,            2) \
X(a, STATIC,   OPTIONAL, INT32,    length,            3) \
X(a, CALLBACK, OPTIONAL, BYTES,    data,             10)
#define nxp_iot_DatastoreRequest_CALLBACK pb_default_field_callback
#define nxp_iot_DatastoreRequest_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define nxp_iot_DatastoreResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1) \
X(a, STATIC,   OPTIONAL, INT32,    length,            2) \
X(a, CALLBACK, OPTIONAL, BYTES,    data,             10)
#define nxp_iot_DatastoreResponse_CALLBACK pb_default_field_callback
#define nxp_iot_DatastoreResponse_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t nxp_iot_DatastoreAdditionalData_msg;
extern const pb_msgdesc_t nxp_iot_DatastoreRequest_msg;
extern const pb_msgdesc_t nxp_iot_DatastoreResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_DatastoreAdditionalData_fields &nxp_iot_DatastoreAdditionalData_msg
#define nxp_iot_DatastoreRequest_fields &nxp_iot_DatastoreRequest_msg
#define nxp_iot_DatastoreResponse_fields &nxp_iot_DatastoreResponse_msg

/* Maximum encoded size of messages (where known) */
/* nxp_iot_DatastoreRequest_size depends on runtime parameters */
/* nxp_iot_DatastoreResponse_size depends on runtime parameters */
#define NXP_IOT_DATASTORE_PB_H_MAX_SIZE          nxp_iot_DatastoreAdditionalData_size
#define nxp_iot_DatastoreAdditionalData_size     2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
