/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_DISPATCHER_PB_H_INCLUDED
#define PB_NXP_IOT_DISPATCHER_PB_H_INCLUDED
#include <pb.h>
#include "Types.pb.h"
#include "Agent.pb.h"
#include "Apdu.pb.h"
#include "Datastore.pb.h"
#include "RPC.pb.h"
#include "Hostcmd.pb.h"
#include "PSA.pb.h"
#include "Proxy.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* The request payload would be either of these */
typedef struct _nxp_iot_RequestPayload {
    pb_size_t which_payload;
    union {
        /* Hello from EdgeLock 2GO cloud service to the EdgeLock 2GO agent.
    
     Used only by EdgeLock 2GO agent. */
        nxp_iot_AgentHelloRequest hello;
        /* * Good Bye from EdgeLock 2GO cloud service to the EdgeLock 2GO agent.
    
     Used only by EdgeLock 2GO agent. */
        nxp_iot_AgentGoodbyeRequest goodbye;
        nxp_iot_AgentCrlRequest crl;
        /* An APDU to a SE.
    
     Used both by EdgeLock 2GO agent and SEMS Lite agent. */
        nxp_iot_ApduRequest apdu;
        /* Message to read and write configuration data.
    
     Used only by EdgeLock 2GO agent. */
        nxp_iot_DatastoreRequest datastore;
        /* Message to contol the host software on the device.
    
     Not implemented. */
        nxp_iot_RpcRequest rpc;
        /* Used only by SEMS Lite Agent */
        nxp_iot_HostControlCmdRequest hostCmd;
        /* Contains requests for a keystore implementing a PSA-style interface 
    
     Used only by EdgeLock 2GO agent. */
        nxp_iot_PsaRequest psa;
        /* Contains requests for the Proxy hello message 
    
     Used only by EdgeLock 2GO agent. */
        nxp_iot_HelloProxyRequest helloProxy;
    } payload;
} nxp_iot_RequestPayload;

typedef struct _nxp_iot_ResponsePayload {
    pb_size_t which_message;
    union {
        nxp_iot_AgentHelloResponse hello;
        nxp_iot_AgentCrlResponse crl;
        nxp_iot_ApduResponse apdu;
        nxp_iot_DatastoreResponse datastore;
        nxp_iot_RpcResponse rpc;
        nxp_iot_PsaResponse psa;
        nxp_iot_HelloProxyResponse helloProxy;
    } message;
} nxp_iot_ResponsePayload;

typedef struct _nxp_iot_EndpointRequest {
    bool has_type;
    nxp_iot_EndpointType type;
    bool has_endpointId;
    uint32_t endpointId;
    pb_callback_t payload;
} nxp_iot_EndpointRequest;

typedef struct _nxp_iot_EndpointRequests {
    pb_callback_t requests;
} nxp_iot_EndpointRequests;

/* Full request from cloud/host to the agent */
typedef struct _nxp_iot_Requests {
    /* An array of RequestPayload */
    pb_callback_t payload;
} nxp_iot_Requests;

/* Consolidated response from the agent to the cloud/host */
typedef struct _nxp_iot_Responses {
    /* An array of ResponsePayload */
    pb_callback_t responses;
} nxp_iot_Responses;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define nxp_iot_RequestPayload_init_default      {0, {nxp_iot_AgentHelloRequest_init_default}}
#define nxp_iot_ResponsePayload_init_default     {0, {nxp_iot_AgentHelloResponse_init_default}}
#define nxp_iot_EndpointRequest_init_default     {false, _nxp_iot_EndpointType_MIN, false, 0, {{NULL}, NULL}}
#define nxp_iot_EndpointRequests_init_default    {{{NULL}, NULL}}
#define nxp_iot_Requests_init_default            {{{NULL}, NULL}}
#define nxp_iot_Responses_init_default           {{{NULL}, NULL}}
#define nxp_iot_RequestPayload_init_zero         {0, {nxp_iot_AgentHelloRequest_init_zero}}
#define nxp_iot_ResponsePayload_init_zero        {0, {nxp_iot_AgentHelloResponse_init_zero}}
#define nxp_iot_EndpointRequest_init_zero        {false, _nxp_iot_EndpointType_MIN, false, 0, {{NULL}, NULL}}
#define nxp_iot_EndpointRequests_init_zero       {{{NULL}, NULL}}
#define nxp_iot_Requests_init_zero               {{{NULL}, NULL}}
#define nxp_iot_Responses_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_RequestPayload_hello_tag         1
#define nxp_iot_RequestPayload_goodbye_tag       2
#define nxp_iot_RequestPayload_crl_tag           3
#define nxp_iot_RequestPayload_apdu_tag          20
#define nxp_iot_RequestPayload_datastore_tag     30
#define nxp_iot_RequestPayload_rpc_tag           40
#define nxp_iot_RequestPayload_hostCmd_tag       50
#define nxp_iot_RequestPayload_psa_tag           60
#define nxp_iot_RequestPayload_helloProxy_tag    70
#define nxp_iot_ResponsePayload_hello_tag        1
#define nxp_iot_ResponsePayload_crl_tag          3
#define nxp_iot_ResponsePayload_apdu_tag         20
#define nxp_iot_ResponsePayload_datastore_tag    30
#define nxp_iot_ResponsePayload_rpc_tag          40
#define nxp_iot_ResponsePayload_psa_tag          60
#define nxp_iot_ResponsePayload_helloProxy_tag   70
#define nxp_iot_EndpointRequest_type_tag         1
#define nxp_iot_EndpointRequest_endpointId_tag   2
#define nxp_iot_EndpointRequest_payload_tag      100
#define nxp_iot_EndpointRequests_requests_tag    1
#define nxp_iot_Requests_payload_tag             1
#define nxp_iot_Responses_responses_tag          1

/* Struct field encoding specification for nanopb */
#define nxp_iot_RequestPayload_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hello,payload.hello),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,goodbye,payload.goodbye),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,crl,payload.crl),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,apdu,payload.apdu),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,datastore,payload.datastore),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rpc,payload.rpc),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hostCmd,payload.hostCmd),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,psa,payload.psa),  60) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,helloProxy,payload.helloProxy),  70)
#define nxp_iot_RequestPayload_CALLBACK NULL
#define nxp_iot_RequestPayload_DEFAULT NULL
#define nxp_iot_RequestPayload_payload_hello_MSGTYPE nxp_iot_AgentHelloRequest
#define nxp_iot_RequestPayload_payload_goodbye_MSGTYPE nxp_iot_AgentGoodbyeRequest
#define nxp_iot_RequestPayload_payload_crl_MSGTYPE nxp_iot_AgentCrlRequest
#define nxp_iot_RequestPayload_payload_apdu_MSGTYPE nxp_iot_ApduRequest
#define nxp_iot_RequestPayload_payload_datastore_MSGTYPE nxp_iot_DatastoreRequest
#define nxp_iot_RequestPayload_payload_rpc_MSGTYPE nxp_iot_RpcRequest
#define nxp_iot_RequestPayload_payload_hostCmd_MSGTYPE nxp_iot_HostControlCmdRequest
#define nxp_iot_RequestPayload_payload_psa_MSGTYPE nxp_iot_PsaRequest
#define nxp_iot_RequestPayload_payload_helloProxy_MSGTYPE nxp_iot_HelloProxyRequest

#define nxp_iot_ResponsePayload_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,hello,message.hello),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,crl,message.crl),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,apdu,message.apdu),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,datastore,message.datastore),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,rpc,message.rpc),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,psa,message.psa),  60) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,helloProxy,message.helloProxy),  70)
#define nxp_iot_ResponsePayload_CALLBACK NULL
#define nxp_iot_ResponsePayload_DEFAULT NULL
#define nxp_iot_ResponsePayload_message_hello_MSGTYPE nxp_iot_AgentHelloResponse
#define nxp_iot_ResponsePayload_message_crl_MSGTYPE nxp_iot_AgentCrlResponse
#define nxp_iot_ResponsePayload_message_apdu_MSGTYPE nxp_iot_ApduResponse
#define nxp_iot_ResponsePayload_message_datastore_MSGTYPE nxp_iot_DatastoreResponse
#define nxp_iot_ResponsePayload_message_rpc_MSGTYPE nxp_iot_RpcResponse
#define nxp_iot_ResponsePayload_message_psa_MSGTYPE nxp_iot_PsaResponse
#define nxp_iot_ResponsePayload_message_helloProxy_MSGTYPE nxp_iot_HelloProxyResponse

#define nxp_iot_EndpointRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   endpointId,        2) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  payload,         100)
#define nxp_iot_EndpointRequest_CALLBACK pb_default_field_callback
#define nxp_iot_EndpointRequest_DEFAULT NULL
#define nxp_iot_EndpointRequest_payload_MSGTYPE nxp_iot_RequestPayload

#define nxp_iot_EndpointRequests_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  requests,          1)
#define nxp_iot_EndpointRequests_CALLBACK pb_default_field_callback
#define nxp_iot_EndpointRequests_DEFAULT NULL
#define nxp_iot_EndpointRequests_requests_MSGTYPE nxp_iot_EndpointRequest

#define nxp_iot_Requests_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  payload,           1)
#define nxp_iot_Requests_CALLBACK pb_default_field_callback
#define nxp_iot_Requests_DEFAULT NULL
#define nxp_iot_Requests_payload_MSGTYPE nxp_iot_RequestPayload

#define nxp_iot_Responses_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  responses,         1)
#define nxp_iot_Responses_CALLBACK pb_default_field_callback
#define nxp_iot_Responses_DEFAULT NULL
#define nxp_iot_Responses_responses_MSGTYPE nxp_iot_ResponsePayload

extern const pb_msgdesc_t nxp_iot_RequestPayload_msg;
extern const pb_msgdesc_t nxp_iot_ResponsePayload_msg;
extern const pb_msgdesc_t nxp_iot_EndpointRequest_msg;
extern const pb_msgdesc_t nxp_iot_EndpointRequests_msg;
extern const pb_msgdesc_t nxp_iot_Requests_msg;
extern const pb_msgdesc_t nxp_iot_Responses_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_RequestPayload_fields &nxp_iot_RequestPayload_msg
#define nxp_iot_ResponsePayload_fields &nxp_iot_ResponsePayload_msg
#define nxp_iot_EndpointRequest_fields &nxp_iot_EndpointRequest_msg
#define nxp_iot_EndpointRequests_fields &nxp_iot_EndpointRequests_msg
#define nxp_iot_Requests_fields &nxp_iot_Requests_msg
#define nxp_iot_Responses_fields &nxp_iot_Responses_msg

/* Maximum encoded size of messages (where known) */
#if defined(nxp_iot_AgentGoodbyeRequest_size) && defined(nxp_iot_AgentCrlRequest_size) && defined(nxp_iot_ApduRequest_size) && defined(nxp_iot_DatastoreRequest_size) && defined(nxp_iot_PsaRequest_size)
union nxp_iot_RequestPayload_payload_size_union {char f2[(6 + nxp_iot_AgentGoodbyeRequest_size)]; char f3[(6 + nxp_iot_AgentCrlRequest_size)]; char f20[(7 + nxp_iot_ApduRequest_size)]; char f30[(7 + nxp_iot_DatastoreRequest_size)]; char f60[(7 + nxp_iot_PsaRequest_size)]; char f0[6279];};
#endif
#if defined(nxp_iot_ApduResponse_size) && defined(nxp_iot_DatastoreResponse_size) && defined(nxp_iot_PsaResponse_size) && defined(nxp_iot_HelloProxyResponse_size)
union nxp_iot_ResponsePayload_message_size_union {char f20[(7 + nxp_iot_ApduResponse_size)]; char f30[(7 + nxp_iot_DatastoreResponse_size)]; char f60[(7 + nxp_iot_PsaResponse_size)]; char f70[(7 + nxp_iot_HelloProxyResponse_size)]; char f0[6279];};
#endif
/* nxp_iot_EndpointRequest_size depends on runtime parameters */
/* nxp_iot_EndpointRequests_size depends on runtime parameters */
/* nxp_iot_Requests_size depends on runtime parameters */
/* nxp_iot_Responses_size depends on runtime parameters */
#if defined(nxp_iot_AgentGoodbyeRequest_size) && defined(nxp_iot_AgentCrlRequest_size) && defined(nxp_iot_ApduRequest_size) && defined(nxp_iot_DatastoreRequest_size) && defined(nxp_iot_PsaRequest_size)
#define NXP_IOT_DISPATCHER_PB_H_MAX_SIZE         nxp_iot_RequestPayload_size
#define nxp_iot_RequestPayload_size              (0 + sizeof(union nxp_iot_RequestPayload_payload_size_union))
#endif
#if defined(nxp_iot_ApduResponse_size) && defined(nxp_iot_DatastoreResponse_size) && defined(nxp_iot_PsaResponse_size) && defined(nxp_iot_HelloProxyResponse_size)
#define nxp_iot_ResponsePayload_size             (0 + sizeof(union nxp_iot_ResponsePayload_message_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
