/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "Dispatcher.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nxp_iot_RequestPayload, nxp_iot_RequestPayload, 4)


PB_BIND(nxp_iot_ResponsePayload, nxp_iot_ResponsePayload, 4)


PB_BIND(nxp_iot_EndpointRequest, nxp_iot_EndpointRequest, 2)


PB_BIND(nxp_iot_EndpointRequests, nxp_iot_EndpointRequests, AUTO)


PB_BIND(nxp_iot_Requests, nxp_iot_Requests, AUTO)


PB_BIND(nxp_iot_Responses, nxp_iot_Responses, AUTO)



