/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_HOSTCMD_PB_H_INCLUDED
#define PB_NXP_IOT_HOSTCMD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _nxp_iot_HostControlCmdRequest_eControlCmd {
    nxp_iot_HostControlCmdRequest_eControlCmd_RESET_SE = 10
} nxp_iot_HostControlCmdRequest_eControlCmd;

/* Struct definitions */
/* doc:host-cmd:start */
typedef struct _nxp_iot_HostControlCmdRequest {
    bool has_hostControlCmd;
    nxp_iot_HostControlCmdRequest_eControlCmd hostControlCmd;
} nxp_iot_HostControlCmdRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _nxp_iot_HostControlCmdRequest_eControlCmd_MIN nxp_iot_HostControlCmdRequest_eControlCmd_RESET_SE
#define _nxp_iot_HostControlCmdRequest_eControlCmd_MAX nxp_iot_HostControlCmdRequest_eControlCmd_RESET_SE
#define _nxp_iot_HostControlCmdRequest_eControlCmd_ARRAYSIZE ((nxp_iot_HostControlCmdRequest_eControlCmd)(nxp_iot_HostControlCmdRequest_eControlCmd_RESET_SE+1))

#define nxp_iot_HostControlCmdRequest_hostControlCmd_ENUMTYPE nxp_iot_HostControlCmdRequest_eControlCmd


/* Initializer values for message structs */
#define nxp_iot_HostControlCmdRequest_init_default {false, _nxp_iot_HostControlCmdRequest_eControlCmd_MIN}
#define nxp_iot_HostControlCmdRequest_init_zero  {false, _nxp_iot_HostControlCmdRequest_eControlCmd_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_HostControlCmdRequest_hostControlCmd_tag 1

/* Struct field encoding specification for nanopb */
#define nxp_iot_HostControlCmdRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    hostControlCmd,    1)
#define nxp_iot_HostControlCmdRequest_CALLBACK NULL
#define nxp_iot_HostControlCmdRequest_DEFAULT (const pb_byte_t*)"\x08\x0a\x00"

extern const pb_msgdesc_t nxp_iot_HostControlCmdRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_HostControlCmdRequest_fields &nxp_iot_HostControlCmdRequest_msg

/* Maximum encoded size of messages (where known) */
#define NXP_IOT_HOSTCMD_PB_H_MAX_SIZE            nxp_iot_HostControlCmdRequest_size
#define nxp_iot_HostControlCmdRequest_size       2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
