/* Copyright 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_PROXY_PB_H_INCLUDED
#define PB_NXP_IOT_PROXY_PB_H_INCLUDED
#include <pb.h>
#include "Agent.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _nxp_iot_HelloProxyRequest {
    char dummy_field;
} nxp_iot_HelloProxyRequest;

typedef struct _nxp_iot_HelloProxyResponse {
    pb_callback_t clientCertificateChain;
    pb_callback_t serverCertificateChain;
    pb_callback_t protocol;
    pb_callback_t cipherSuite;
    pb_callback_t serverHostname;
    pb_callback_t correlationId;
    /* Add connection Status to the Hello Proxy response to communicate Device Link the status of the connection */
    bool has_connectionStatus;
    nxp_iot_UpdateStatusReport_UpdateStatus connectionStatus;
    pb_callback_t customerId;
} nxp_iot_HelloProxyResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define nxp_iot_HelloProxyRequest_init_default   {0}
#define nxp_iot_HelloProxyResponse_init_default  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _nxp_iot_UpdateStatusReport_UpdateStatus_MIN, {{NULL}, NULL}}
#define nxp_iot_HelloProxyRequest_init_zero      {0}
#define nxp_iot_HelloProxyResponse_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _nxp_iot_UpdateStatusReport_UpdateStatus_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_HelloProxyResponse_clientCertificateChain_tag 1
#define nxp_iot_HelloProxyResponse_serverCertificateChain_tag 2
#define nxp_iot_HelloProxyResponse_protocol_tag  3
#define nxp_iot_HelloProxyResponse_cipherSuite_tag 4
#define nxp_iot_HelloProxyResponse_serverHostname_tag 5
#define nxp_iot_HelloProxyResponse_correlationId_tag 6
#define nxp_iot_HelloProxyResponse_connectionStatus_tag 7
#define nxp_iot_HelloProxyResponse_customerId_tag 8

/* Struct field encoding specification for nanopb */
#define nxp_iot_HelloProxyRequest_FIELDLIST(X, a) \

#define nxp_iot_HelloProxyRequest_CALLBACK NULL
#define nxp_iot_HelloProxyRequest_DEFAULT NULL

#define nxp_iot_HelloProxyResponse_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    clientCertificateChain,   1) \
X(a, CALLBACK, OPTIONAL, BYTES,    serverCertificateChain,   2) \
X(a, CALLBACK, OPTIONAL, BYTES,    protocol,          3) \
X(a, CALLBACK, OPTIONAL, BYTES,    cipherSuite,       4) \
X(a, CALLBACK, OPTIONAL, BYTES,    serverHostname,    5) \
X(a, CALLBACK, OPTIONAL, BYTES,    correlationId,     6) \
X(a, STATIC,   OPTIONAL, UENUM,    connectionStatus,   7) \
X(a, CALLBACK, OPTIONAL, BYTES,    customerId,        8)
#define nxp_iot_HelloProxyResponse_CALLBACK pb_default_field_callback
#define nxp_iot_HelloProxyResponse_DEFAULT NULL

extern const pb_msgdesc_t nxp_iot_HelloProxyRequest_msg;
extern const pb_msgdesc_t nxp_iot_HelloProxyResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_HelloProxyRequest_fields &nxp_iot_HelloProxyRequest_msg
#define nxp_iot_HelloProxyResponse_fields &nxp_iot_HelloProxyResponse_msg

/* Maximum encoded size of messages (where known) */
/* nxp_iot_HelloProxyResponse_size depends on runtime parameters */
#define NXP_IOT_PROXY_PB_H_MAX_SIZE              nxp_iot_HelloProxyRequest_size
#define nxp_iot_HelloProxyRequest_size           0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
