/* Copyright 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "Proxy.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nxp_iot_HelloProxyRequest, nxp_iot_HelloProxyRequest, AUTO)


PB_BIND(nxp_iot_HelloProxyResponse, nxp_iot_HelloProxyResponse, AUTO)



