/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "PSA.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nxp_iot_GetVersionRequest, nxp_iot_GetVersionRequest, AUTO)


PB_BIND(nxp_iot_GetVersionResponse, nxp_iot_GetVersionResponse, AUTO)


PB_BIND(nxp_iot_DestroyKeyRequest, nxp_iot_DestroyKeyRequest, AUTO)


PB_BIND(nxp_iot_DestroyKeyResponse, nxp_iot_DestroyKeyResponse, AUTO)


PB_BIND(nxp_iot_ImportKeyRequest, nxp_iot_ImportKeyRequest, AUTO)


PB_BIND(nxp_iot_ImportKeyResponse, nxp_iot_ImportKeyResponse, AUTO)


PB_BIND(nxp_iot_CreateObjectRequest, nxp_iot_CreateObjectRequest, AUTO)


PB_BIND(nxp_iot_CreateObjectResponse, nxp_iot_CreateObjectResponse, AUTO)


PB_BIND(nxp_iot_WriteObjectRequest, nxp_iot_WriteObjectRequest, AUTO)


PB_BIND(nxp_iot_WriteObjectResponse, nxp_iot_WriteObjectResponse, AUTO)


PB_BIND(nxp_iot_ReadObjectRequest, nxp_iot_ReadObjectRequest, AUTO)


PB_BIND(nxp_iot_ReadObjectResponse, nxp_iot_ReadObjectResponse, AUTO)


PB_BIND(nxp_iot_RemoveObjectRequest, nxp_iot_RemoveObjectRequest, AUTO)


PB_BIND(nxp_iot_RemoveObjectResponse, nxp_iot_RemoveObjectResponse, AUTO)


PB_BIND(nxp_iot_PsaAdditionalData, nxp_iot_PsaAdditionalData, AUTO)


PB_BIND(nxp_iot_PsaRequest, nxp_iot_PsaRequest, AUTO)


PB_BIND(nxp_iot_PsaResponse, nxp_iot_PsaResponse, AUTO)







