/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_PSA_PB_H_INCLUDED
#define PB_NXP_IOT_PSA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _nxp_iot_KeyDataFormat {
    nxp_iot_KeyDataFormat_UNKNOWN = 0,
    nxp_iot_KeyDataFormat_S50 = 1
} nxp_iot_KeyDataFormat;

typedef enum _nxp_iot_StatusCode {
    nxp_iot_StatusCode_PSA_SUCCESS = 0,
    nxp_iot_StatusCode_PSA_ERROR_GENERIC_ERROR = -132,
    nxp_iot_StatusCode_PSA_ERROR_NOT_SUPPORTED = -134,
    nxp_iot_StatusCode_PSA_ERROR_NOT_PERMITTED = -133,
    nxp_iot_StatusCode_PSA_ERROR_BUFFER_TOO_SMALL = -138,
    nxp_iot_StatusCode_PSA_ERROR_ALREADY_EXISTS = -139,
    nxp_iot_StatusCode_PSA_ERROR_DOES_NOT_EXIST = -140,
    nxp_iot_StatusCode_PSA_ERROR_BAD_STATE = -137,
    nxp_iot_StatusCode_PSA_ERROR_INVALID_ARGUMENT = -135,
    nxp_iot_StatusCode_PSA_ERROR_INSUFFICIENT_MEMORY = -141,
    nxp_iot_StatusCode_PSA_ERROR_INSUFFICIENT_STORAGE = -142,
    nxp_iot_StatusCode_PSA_ERROR_COMMUNICATION_FAILURE = -145,
    nxp_iot_StatusCode_PSA_ERROR_STORAGE_FAILURE = -146,
    nxp_iot_StatusCode_PSA_ERROR_DATA_CORRUPT = -152,
    nxp_iot_StatusCode_PSA_ERROR_DATA_INVALID = -153,
    nxp_iot_StatusCode_PSA_ERROR_HARDWARE_FAILURE = -147,
    nxp_iot_StatusCode_PSA_ERROR_CORRUPTION_DETECTED = -151,
    nxp_iot_StatusCode_PSA_ERROR_INSUFFICIENT_ENTROPY = -148,
    nxp_iot_StatusCode_PSA_ERROR_INVALID_SIGNATURE = -149,
    nxp_iot_StatusCode_PSA_ERROR_INVALID_PADDING = -150,
    nxp_iot_StatusCode_PSA_ERROR_INSUFFICIENT_DATA = -143,
    nxp_iot_StatusCode_PSA_ERROR_INVALID_HANDLE = -136
} nxp_iot_StatusCode;

/* Struct definitions */
typedef struct _nxp_iot_GetVersionRequest {
    char dummy_field;
} nxp_iot_GetVersionRequest;

typedef struct _nxp_iot_GetVersionResponse {
    /* Convey information about the version of a particular service. Encoded in 3 bytes, starting
 from LSB: patch version, minor version, major version (e.g. version 1.2.3 = 0x00010203). */
    bool has_crypto_api_version;
    uint32_t crypto_api_version;
    bool has_storage_api_version;
    uint32_t storage_api_version;
    /* Notify the server about supported key data formats. In case the field is omitted, no
 restrictions on key data formats do apply. */
    pb_size_t supported_key_data_formats_count;
    nxp_iot_KeyDataFormat supported_key_data_formats[1];
    bool has_max_raw_key_size;
    uint32_t max_raw_key_size;
} nxp_iot_GetVersionResponse;

typedef struct _nxp_iot_DestroyKeyRequest {
    bool has_identifier;
    uint32_t identifier;
} nxp_iot_DestroyKeyRequest;

typedef struct _nxp_iot_DestroyKeyResponse {
    bool has_status;
    nxp_iot_StatusCode status;
} nxp_iot_DestroyKeyResponse;

typedef struct _nxp_iot_ImportKeyRequest {
    /* Key attributes. The values allowed in these fields follow the 
 PSA Cryptography API specification. */
    bool has_identifier;
    uint32_t identifier;
    bool has_type;
    uint32_t type;
    bool has_usage;
    uint32_t usage;
    bool has_algorithm;
    uint32_t algorithm;
    bool has_lifetime;
    uint32_t lifetime;
    bool has_key_bits;
    uint32_t key_bits;
    /* This is an opaque key-blob. */
    pb_bytes_array_t *data;
    bool has_key_data_format;
    nxp_iot_KeyDataFormat key_data_format;
} nxp_iot_ImportKeyRequest;

typedef struct _nxp_iot_ImportKeyResponse {
    bool has_status;
    nxp_iot_StatusCode status;
} nxp_iot_ImportKeyResponse;

typedef struct _nxp_iot_CreateObjectRequest {
    /* Note, the PSA Storage API does take a 64 bit int here. However, we are only concerned about
 the object id within one partition. */
    bool has_identifier;
    uint32_t identifier;
    bool has_create_flags;
    uint32_t create_flags;
    pb_callback_t data;
} nxp_iot_CreateObjectRequest;

typedef struct _nxp_iot_CreateObjectResponse {
    bool has_status;
    nxp_iot_StatusCode status;
} nxp_iot_CreateObjectResponse;

typedef struct _nxp_iot_WriteObjectRequest {
    /* Note, the PSA Storage API does take a 64 bit int here. However, we are only concerned about
 the object id within one partition. */
    bool has_identifier;
    uint32_t identifier;
    bool has_offset;
    uint32_t offset;
    pb_callback_t data;
} nxp_iot_WriteObjectRequest;

typedef struct _nxp_iot_WriteObjectResponse {
    bool has_status;
    nxp_iot_StatusCode status;
} nxp_iot_WriteObjectResponse;

typedef struct _nxp_iot_ReadObjectRequest {
    /* Note, the PSA Storage API does take a 64 bit int here. However, we are only concerned about
 the object id within one partition. */
    bool has_identifier;
    uint32_t identifier;
    bool has_offset;
    uint32_t offset;
    bool has_length;
    uint32_t length;
} nxp_iot_ReadObjectRequest;

typedef struct _nxp_iot_ReadObjectResponse {
    bool has_status;
    nxp_iot_StatusCode status;
    pb_bytes_array_t *data;
} nxp_iot_ReadObjectResponse;

typedef struct _nxp_iot_RemoveObjectRequest {
    /* Note, the PSA Storage API does take a 64 bit int here. However, we are only concerned about
 the object id within one partition. */
    bool has_identifier;
    uint32_t identifier;
} nxp_iot_RemoveObjectRequest;

typedef struct _nxp_iot_RemoveObjectResponse {
    bool has_status;
    nxp_iot_StatusCode status;
} nxp_iot_RemoveObjectResponse;

typedef struct _nxp_iot_PsaAdditionalData {
    char dummy_field;
} nxp_iot_PsaAdditionalData;

typedef struct _nxp_iot_PsaRequest {
    pb_size_t which_command;
    union {
        nxp_iot_GetVersionRequest get_version;
        nxp_iot_DestroyKeyRequest destroy_key;
        nxp_iot_ImportKeyRequest import_key;
        nxp_iot_CreateObjectRequest create_object;
        nxp_iot_WriteObjectRequest write_object;
        nxp_iot_ReadObjectRequest read_object;
        nxp_iot_RemoveObjectRequest remove_object;
    } command;
} nxp_iot_PsaRequest;

typedef struct _nxp_iot_PsaResponse {
    pb_size_t which_response;
    union {
        nxp_iot_GetVersionResponse get_version;
        nxp_iot_DestroyKeyResponse destroy_key;
        nxp_iot_ImportKeyResponse import_key;
        nxp_iot_CreateObjectResponse create_object;
        nxp_iot_WriteObjectResponse write_object;
        nxp_iot_ReadObjectResponse read_object;
        nxp_iot_RemoveObjectResponse remove_object;
    } response;
} nxp_iot_PsaResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _nxp_iot_KeyDataFormat_MIN nxp_iot_KeyDataFormat_UNKNOWN
#define _nxp_iot_KeyDataFormat_MAX nxp_iot_KeyDataFormat_S50
#define _nxp_iot_KeyDataFormat_ARRAYSIZE ((nxp_iot_KeyDataFormat)(nxp_iot_KeyDataFormat_S50+1))

#define _nxp_iot_StatusCode_MIN nxp_iot_StatusCode_PSA_ERROR_DATA_INVALID
#define _nxp_iot_StatusCode_MAX nxp_iot_StatusCode_PSA_SUCCESS
#define _nxp_iot_StatusCode_ARRAYSIZE ((nxp_iot_StatusCode)(nxp_iot_StatusCode_PSA_SUCCESS+1))


#define nxp_iot_GetVersionResponse_supported_key_data_formats_ENUMTYPE nxp_iot_KeyDataFormat


#define nxp_iot_DestroyKeyResponse_status_ENUMTYPE nxp_iot_StatusCode

#define nxp_iot_ImportKeyRequest_key_data_format_ENUMTYPE nxp_iot_KeyDataFormat

#define nxp_iot_ImportKeyResponse_status_ENUMTYPE nxp_iot_StatusCode


#define nxp_iot_CreateObjectResponse_status_ENUMTYPE nxp_iot_StatusCode


#define nxp_iot_WriteObjectResponse_status_ENUMTYPE nxp_iot_StatusCode


#define nxp_iot_ReadObjectResponse_status_ENUMTYPE nxp_iot_StatusCode


#define nxp_iot_RemoveObjectResponse_status_ENUMTYPE nxp_iot_StatusCode





/* Initializer values for message structs */
#define nxp_iot_GetVersionRequest_init_default   {0}
#define nxp_iot_GetVersionResponse_init_default  {false, 0, false, 0, 0, {_nxp_iot_KeyDataFormat_MIN}, false, 0}
#define nxp_iot_DestroyKeyRequest_init_default   {false, 0}
#define nxp_iot_DestroyKeyResponse_init_default  {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_ImportKeyRequest_init_default    {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, NULL, false, _nxp_iot_KeyDataFormat_MIN}
#define nxp_iot_ImportKeyResponse_init_default   {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_CreateObjectRequest_init_default {false, 0, false, 0, {{NULL}, NULL}}
#define nxp_iot_CreateObjectResponse_init_default {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_WriteObjectRequest_init_default  {false, 0, false, 0, {{NULL}, NULL}}
#define nxp_iot_WriteObjectResponse_init_default {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_ReadObjectRequest_init_default   {false, 0, false, 0, false, 0}
#define nxp_iot_ReadObjectResponse_init_default  {false, _nxp_iot_StatusCode_MIN, NULL}
#define nxp_iot_RemoveObjectRequest_init_default {false, 0}
#define nxp_iot_RemoveObjectResponse_init_default {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_PsaAdditionalData_init_default   {0}
#define nxp_iot_PsaRequest_init_default          {0, {nxp_iot_GetVersionRequest_init_default}}
#define nxp_iot_PsaResponse_init_default         {0, {nxp_iot_GetVersionResponse_init_default}}
#define nxp_iot_GetVersionRequest_init_zero      {0}
#define nxp_iot_GetVersionResponse_init_zero     {false, 0, false, 0, 0, {_nxp_iot_KeyDataFormat_MIN}, false, 0}
#define nxp_iot_DestroyKeyRequest_init_zero      {false, 0}
#define nxp_iot_DestroyKeyResponse_init_zero     {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_ImportKeyRequest_init_zero       {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, NULL, false, _nxp_iot_KeyDataFormat_MIN}
#define nxp_iot_ImportKeyResponse_init_zero      {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_CreateObjectRequest_init_zero    {false, 0, false, 0, {{NULL}, NULL}}
#define nxp_iot_CreateObjectResponse_init_zero   {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_WriteObjectRequest_init_zero     {false, 0, false, 0, {{NULL}, NULL}}
#define nxp_iot_WriteObjectResponse_init_zero    {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_ReadObjectRequest_init_zero      {false, 0, false, 0, false, 0}
#define nxp_iot_ReadObjectResponse_init_zero     {false, _nxp_iot_StatusCode_MIN, NULL}
#define nxp_iot_RemoveObjectRequest_init_zero    {false, 0}
#define nxp_iot_RemoveObjectResponse_init_zero   {false, _nxp_iot_StatusCode_MIN}
#define nxp_iot_PsaAdditionalData_init_zero      {0}
#define nxp_iot_PsaRequest_init_zero             {0, {nxp_iot_GetVersionRequest_init_zero}}
#define nxp_iot_PsaResponse_init_zero            {0, {nxp_iot_GetVersionResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_GetVersionResponse_crypto_api_version_tag 1
#define nxp_iot_GetVersionResponse_storage_api_version_tag 2
#define nxp_iot_GetVersionResponse_supported_key_data_formats_tag 4
#define nxp_iot_GetVersionResponse_max_raw_key_size_tag 5
#define nxp_iot_DestroyKeyRequest_identifier_tag 1
#define nxp_iot_DestroyKeyResponse_status_tag    1
#define nxp_iot_ImportKeyRequest_identifier_tag  1
#define nxp_iot_ImportKeyRequest_type_tag        2
#define nxp_iot_ImportKeyRequest_usage_tag       3
#define nxp_iot_ImportKeyRequest_algorithm_tag   4
#define nxp_iot_ImportKeyRequest_lifetime_tag    5
#define nxp_iot_ImportKeyRequest_key_bits_tag    6
#define nxp_iot_ImportKeyRequest_data_tag        10
#define nxp_iot_ImportKeyRequest_key_data_format_tag 11
#define nxp_iot_ImportKeyResponse_status_tag     1
#define nxp_iot_CreateObjectRequest_identifier_tag 1
#define nxp_iot_CreateObjectRequest_create_flags_tag 2
#define nxp_iot_CreateObjectRequest_data_tag     10
#define nxp_iot_CreateObjectResponse_status_tag  1
#define nxp_iot_WriteObjectRequest_identifier_tag 1
#define nxp_iot_WriteObjectRequest_offset_tag    2
#define nxp_iot_WriteObjectRequest_data_tag      10
#define nxp_iot_WriteObjectResponse_status_tag   1
#define nxp_iot_ReadObjectRequest_identifier_tag 1
#define nxp_iot_ReadObjectRequest_offset_tag     2
#define nxp_iot_ReadObjectRequest_length_tag     3
#define nxp_iot_ReadObjectResponse_status_tag    1
#define nxp_iot_ReadObjectResponse_data_tag      10
#define nxp_iot_RemoveObjectRequest_identifier_tag 1
#define nxp_iot_RemoveObjectResponse_status_tag  1
#define nxp_iot_PsaRequest_get_version_tag       1
#define nxp_iot_PsaRequest_destroy_key_tag       2
#define nxp_iot_PsaRequest_import_key_tag        3
#define nxp_iot_PsaRequest_create_object_tag     4
#define nxp_iot_PsaRequest_write_object_tag      5
#define nxp_iot_PsaRequest_read_object_tag       6
#define nxp_iot_PsaRequest_remove_object_tag     7
#define nxp_iot_PsaResponse_get_version_tag      1
#define nxp_iot_PsaResponse_destroy_key_tag      2
#define nxp_iot_PsaResponse_import_key_tag       3
#define nxp_iot_PsaResponse_create_object_tag    4
#define nxp_iot_PsaResponse_write_object_tag     5
#define nxp_iot_PsaResponse_read_object_tag      6
#define nxp_iot_PsaResponse_remove_object_tag    7

/* Struct field encoding specification for nanopb */
#define nxp_iot_GetVersionRequest_FIELDLIST(X, a) \

#define nxp_iot_GetVersionRequest_CALLBACK NULL
#define nxp_iot_GetVersionRequest_DEFAULT NULL

#define nxp_iot_GetVersionResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED32,  crypto_api_version,   1) \
X(a, STATIC,   OPTIONAL, FIXED32,  storage_api_version,   2) \
X(a, STATIC,   REPEATED, UENUM,    supported_key_data_formats,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   max_raw_key_size,   5)
#define nxp_iot_GetVersionResponse_CALLBACK NULL
#define nxp_iot_GetVersionResponse_DEFAULT NULL

#define nxp_iot_DestroyKeyRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   identifier,        1)
#define nxp_iot_DestroyKeyRequest_CALLBACK NULL
#define nxp_iot_DestroyKeyRequest_DEFAULT NULL

#define nxp_iot_DestroyKeyResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, ENUM,     status,            1)
#define nxp_iot_DestroyKeyResponse_CALLBACK NULL
#define nxp_iot_DestroyKeyResponse_DEFAULT NULL

#define nxp_iot_ImportKeyRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   identifier,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   type,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   usage,             3) \
X(a, STATIC,   OPTIONAL, UINT32,   algorithm,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   lifetime,          5) \
X(a, STATIC,   OPTIONAL, UINT32,   key_bits,          6) \
X(a, POINTER,  OPTIONAL, BYTES,    data,             10) \
X(a, STATIC,   OPTIONAL, UENUM,    key_data_format,  11)
#define nxp_iot_ImportKeyRequest_CALLBACK NULL
#define nxp_iot_ImportKeyRequest_DEFAULT NULL

#define nxp_iot_ImportKeyResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, ENUM,     status,            1)
#define nxp_iot_ImportKeyResponse_CALLBACK NULL
#define nxp_iot_ImportKeyResponse_DEFAULT NULL

#define nxp_iot_CreateObjectRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   identifier,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   create_flags,      2) \
X(a, CALLBACK, OPTIONAL, BYTES,    data,             10)
#define nxp_iot_CreateObjectRequest_CALLBACK pb_default_field_callback
#define nxp_iot_CreateObjectRequest_DEFAULT NULL

#define nxp_iot_CreateObjectResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, ENUM,     status,            1)
#define nxp_iot_CreateObjectResponse_CALLBACK NULL
#define nxp_iot_CreateObjectResponse_DEFAULT NULL

#define nxp_iot_WriteObjectRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   identifier,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   offset,            2) \
X(a, CALLBACK, OPTIONAL, BYTES,    data,             10)
#define nxp_iot_WriteObjectRequest_CALLBACK pb_default_field_callback
#define nxp_iot_WriteObjectRequest_DEFAULT NULL

#define nxp_iot_WriteObjectResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, ENUM,     status,            1)
#define nxp_iot_WriteObjectResponse_CALLBACK NULL
#define nxp_iot_WriteObjectResponse_DEFAULT NULL

#define nxp_iot_ReadObjectRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   identifier,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   offset,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   length,            3)
#define nxp_iot_ReadObjectRequest_CALLBACK NULL
#define nxp_iot_ReadObjectRequest_DEFAULT NULL

#define nxp_iot_ReadObjectResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, ENUM,     status,            1) \
X(a, POINTER,  OPTIONAL, BYTES,    data,             10)
#define nxp_iot_ReadObjectResponse_CALLBACK NULL
#define nxp_iot_ReadObjectResponse_DEFAULT NULL

#define nxp_iot_RemoveObjectRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   identifier,        1)
#define nxp_iot_RemoveObjectRequest_CALLBACK NULL
#define nxp_iot_RemoveObjectRequest_DEFAULT NULL

#define nxp_iot_RemoveObjectResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, ENUM,     status,            1)
#define nxp_iot_RemoveObjectResponse_CALLBACK NULL
#define nxp_iot_RemoveObjectResponse_DEFAULT NULL

#define nxp_iot_PsaAdditionalData_FIELDLIST(X, a) \

#define nxp_iot_PsaAdditionalData_CALLBACK NULL
#define nxp_iot_PsaAdditionalData_DEFAULT NULL

#define nxp_iot_PsaRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_version,command.get_version),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,destroy_key,command.destroy_key),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,import_key,command.import_key),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,create_object,command.create_object),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,write_object,command.write_object),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,read_object,command.read_object),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,remove_object,command.remove_object),   7)
#define nxp_iot_PsaRequest_CALLBACK NULL
#define nxp_iot_PsaRequest_DEFAULT NULL
#define nxp_iot_PsaRequest_command_get_version_MSGTYPE nxp_iot_GetVersionRequest
#define nxp_iot_PsaRequest_command_destroy_key_MSGTYPE nxp_iot_DestroyKeyRequest
#define nxp_iot_PsaRequest_command_import_key_MSGTYPE nxp_iot_ImportKeyRequest
#define nxp_iot_PsaRequest_command_create_object_MSGTYPE nxp_iot_CreateObjectRequest
#define nxp_iot_PsaRequest_command_write_object_MSGTYPE nxp_iot_WriteObjectRequest
#define nxp_iot_PsaRequest_command_read_object_MSGTYPE nxp_iot_ReadObjectRequest
#define nxp_iot_PsaRequest_command_remove_object_MSGTYPE nxp_iot_RemoveObjectRequest

#define nxp_iot_PsaResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,get_version,response.get_version),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,destroy_key,response.destroy_key),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,import_key,response.import_key),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,create_object,response.create_object),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,write_object,response.write_object),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,read_object,response.read_object),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,remove_object,response.remove_object),   7)
#define nxp_iot_PsaResponse_CALLBACK NULL
#define nxp_iot_PsaResponse_DEFAULT NULL
#define nxp_iot_PsaResponse_response_get_version_MSGTYPE nxp_iot_GetVersionResponse
#define nxp_iot_PsaResponse_response_destroy_key_MSGTYPE nxp_iot_DestroyKeyResponse
#define nxp_iot_PsaResponse_response_import_key_MSGTYPE nxp_iot_ImportKeyResponse
#define nxp_iot_PsaResponse_response_create_object_MSGTYPE nxp_iot_CreateObjectResponse
#define nxp_iot_PsaResponse_response_write_object_MSGTYPE nxp_iot_WriteObjectResponse
#define nxp_iot_PsaResponse_response_read_object_MSGTYPE nxp_iot_ReadObjectResponse
#define nxp_iot_PsaResponse_response_remove_object_MSGTYPE nxp_iot_RemoveObjectResponse

extern const pb_msgdesc_t nxp_iot_GetVersionRequest_msg;
extern const pb_msgdesc_t nxp_iot_GetVersionResponse_msg;
extern const pb_msgdesc_t nxp_iot_DestroyKeyRequest_msg;
extern const pb_msgdesc_t nxp_iot_DestroyKeyResponse_msg;
extern const pb_msgdesc_t nxp_iot_ImportKeyRequest_msg;
extern const pb_msgdesc_t nxp_iot_ImportKeyResponse_msg;
extern const pb_msgdesc_t nxp_iot_CreateObjectRequest_msg;
extern const pb_msgdesc_t nxp_iot_CreateObjectResponse_msg;
extern const pb_msgdesc_t nxp_iot_WriteObjectRequest_msg;
extern const pb_msgdesc_t nxp_iot_WriteObjectResponse_msg;
extern const pb_msgdesc_t nxp_iot_ReadObjectRequest_msg;
extern const pb_msgdesc_t nxp_iot_ReadObjectResponse_msg;
extern const pb_msgdesc_t nxp_iot_RemoveObjectRequest_msg;
extern const pb_msgdesc_t nxp_iot_RemoveObjectResponse_msg;
extern const pb_msgdesc_t nxp_iot_PsaAdditionalData_msg;
extern const pb_msgdesc_t nxp_iot_PsaRequest_msg;
extern const pb_msgdesc_t nxp_iot_PsaResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_GetVersionRequest_fields &nxp_iot_GetVersionRequest_msg
#define nxp_iot_GetVersionResponse_fields &nxp_iot_GetVersionResponse_msg
#define nxp_iot_DestroyKeyRequest_fields &nxp_iot_DestroyKeyRequest_msg
#define nxp_iot_DestroyKeyResponse_fields &nxp_iot_DestroyKeyResponse_msg
#define nxp_iot_ImportKeyRequest_fields &nxp_iot_ImportKeyRequest_msg
#define nxp_iot_ImportKeyResponse_fields &nxp_iot_ImportKeyResponse_msg
#define nxp_iot_CreateObjectRequest_fields &nxp_iot_CreateObjectRequest_msg
#define nxp_iot_CreateObjectResponse_fields &nxp_iot_CreateObjectResponse_msg
#define nxp_iot_WriteObjectRequest_fields &nxp_iot_WriteObjectRequest_msg
#define nxp_iot_WriteObjectResponse_fields &nxp_iot_WriteObjectResponse_msg
#define nxp_iot_ReadObjectRequest_fields &nxp_iot_ReadObjectRequest_msg
#define nxp_iot_ReadObjectResponse_fields &nxp_iot_ReadObjectResponse_msg
#define nxp_iot_RemoveObjectRequest_fields &nxp_iot_RemoveObjectRequest_msg
#define nxp_iot_RemoveObjectResponse_fields &nxp_iot_RemoveObjectResponse_msg
#define nxp_iot_PsaAdditionalData_fields &nxp_iot_PsaAdditionalData_msg
#define nxp_iot_PsaRequest_fields &nxp_iot_PsaRequest_msg
#define nxp_iot_PsaResponse_fields &nxp_iot_PsaResponse_msg

/* Maximum encoded size of messages (where known) */
/* nxp_iot_ImportKeyRequest_size depends on runtime parameters */
/* nxp_iot_CreateObjectRequest_size depends on runtime parameters */
/* nxp_iot_WriteObjectRequest_size depends on runtime parameters */
/* nxp_iot_ReadObjectResponse_size depends on runtime parameters */
/* nxp_iot_PsaRequest_size depends on runtime parameters */
/* nxp_iot_PsaResponse_size depends on runtime parameters */
#define NXP_IOT_PSA_PB_H_MAX_SIZE                nxp_iot_GetVersionResponse_size
#define nxp_iot_CreateObjectResponse_size        11
#define nxp_iot_DestroyKeyRequest_size           6
#define nxp_iot_DestroyKeyResponse_size          11
#define nxp_iot_GetVersionRequest_size           0
#define nxp_iot_GetVersionResponse_size          19
#define nxp_iot_ImportKeyResponse_size           11
#define nxp_iot_PsaAdditionalData_size           0
#define nxp_iot_ReadObjectRequest_size           18
#define nxp_iot_RemoveObjectRequest_size         6
#define nxp_iot_RemoveObjectResponse_size        11
#define nxp_iot_WriteObjectResponse_size         11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
