/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "RPC.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nxp_iot_ArgumentPayload, nxp_iot_ArgumentPayload, 2)


PB_BIND(nxp_iot_Argument, nxp_iot_Argument, 2)


PB_BIND(nxp_iot_RpcRequest, nxp_iot_RpcRequest, 4)


PB_BIND(nxp_iot_RpcResponse, nxp_iot_RpcResponse, 4)



