/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_RPC_PB_H_INCLUDED
#define PB_NXP_IOT_RPC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) nxp_iot_ArgumentPayload_bytes_arg_t;
typedef struct _nxp_iot_ArgumentPayload {
    pb_size_t which_data;
    union {
        uint32_t uint32_arg;
        int32_t int32_arg;
        nxp_iot_ArgumentPayload_bytes_arg_t bytes_arg;
        char string_arg[1024];
    } data;
} nxp_iot_ArgumentPayload;

typedef struct _nxp_iot_Argument {
    bool has_pos;
    int32_t pos;
    bool has_payload;
    nxp_iot_ArgumentPayload payload;
} nxp_iot_Argument;

typedef struct _nxp_iot_RpcRequest {
    bool has_id;
    int32_t id;
    pb_size_t arg_count;
    nxp_iot_Argument arg[6];
} nxp_iot_RpcRequest;

typedef struct _nxp_iot_RpcResponse {
    bool has_id;
    int32_t id;
    pb_size_t arg_count;
    nxp_iot_Argument arg[6];
} nxp_iot_RpcResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define nxp_iot_ArgumentPayload_init_default     {0, {0}}
#define nxp_iot_Argument_init_default            {false, 0, false, nxp_iot_ArgumentPayload_init_default}
#define nxp_iot_RpcRequest_init_default          {false, 0, 0, {nxp_iot_Argument_init_default, nxp_iot_Argument_init_default, nxp_iot_Argument_init_default, nxp_iot_Argument_init_default, nxp_iot_Argument_init_default, nxp_iot_Argument_init_default}}
#define nxp_iot_RpcResponse_init_default         {false, 0, 0, {nxp_iot_Argument_init_default, nxp_iot_Argument_init_default, nxp_iot_Argument_init_default, nxp_iot_Argument_init_default, nxp_iot_Argument_init_default, nxp_iot_Argument_init_default}}
#define nxp_iot_ArgumentPayload_init_zero        {0, {0}}
#define nxp_iot_Argument_init_zero               {false, 0, false, nxp_iot_ArgumentPayload_init_zero}
#define nxp_iot_RpcRequest_init_zero             {false, 0, 0, {nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero}}
#define nxp_iot_RpcResponse_init_zero            {false, 0, 0, {nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero, nxp_iot_Argument_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_ArgumentPayload_uint32_arg_tag   2
#define nxp_iot_ArgumentPayload_int32_arg_tag    3
#define nxp_iot_ArgumentPayload_bytes_arg_tag    4
#define nxp_iot_ArgumentPayload_string_arg_tag   5
#define nxp_iot_Argument_pos_tag                 1
#define nxp_iot_Argument_payload_tag             10
#define nxp_iot_RpcRequest_id_tag                1
#define nxp_iot_RpcRequest_arg_tag               10
#define nxp_iot_RpcResponse_id_tag               1
#define nxp_iot_RpcResponse_arg_tag              10

/* Struct field encoding specification for nanopb */
#define nxp_iot_ArgumentPayload_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (data,uint32_arg,data.uint32_arg),   2) \
X(a, STATIC,   ONEOF,    INT32,    (data,int32_arg,data.int32_arg),   3) \
X(a, STATIC,   ONEOF,    BYTES,    (data,bytes_arg,data.bytes_arg),   4) \
X(a, STATIC,   ONEOF,    STRING,   (data,string_arg,data.string_arg),   5)
#define nxp_iot_ArgumentPayload_CALLBACK NULL
#define nxp_iot_ArgumentPayload_DEFAULT NULL

#define nxp_iot_Argument_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    pos,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  payload,          10)
#define nxp_iot_Argument_CALLBACK NULL
#define nxp_iot_Argument_DEFAULT NULL
#define nxp_iot_Argument_payload_MSGTYPE nxp_iot_ArgumentPayload

#define nxp_iot_RpcRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    id,                1) \
X(a, STATIC,   REPEATED, MESSAGE,  arg,              10)
#define nxp_iot_RpcRequest_CALLBACK NULL
#define nxp_iot_RpcRequest_DEFAULT NULL
#define nxp_iot_RpcRequest_arg_MSGTYPE nxp_iot_Argument

#define nxp_iot_RpcResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    id,                1) \
X(a, STATIC,   REPEATED, MESSAGE,  arg,              10)
#define nxp_iot_RpcResponse_CALLBACK NULL
#define nxp_iot_RpcResponse_DEFAULT NULL
#define nxp_iot_RpcResponse_arg_MSGTYPE nxp_iot_Argument

extern const pb_msgdesc_t nxp_iot_ArgumentPayload_msg;
extern const pb_msgdesc_t nxp_iot_Argument_msg;
extern const pb_msgdesc_t nxp_iot_RpcRequest_msg;
extern const pb_msgdesc_t nxp_iot_RpcResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_ArgumentPayload_fields &nxp_iot_ArgumentPayload_msg
#define nxp_iot_Argument_fields &nxp_iot_Argument_msg
#define nxp_iot_RpcRequest_fields &nxp_iot_RpcRequest_msg
#define nxp_iot_RpcResponse_fields &nxp_iot_RpcResponse_msg

/* Maximum encoded size of messages (where known) */
#define NXP_IOT_RPC_PB_H_MAX_SIZE                nxp_iot_RpcRequest_size
#define nxp_iot_ArgumentPayload_size             1027
#define nxp_iot_Argument_size                    1041
#define nxp_iot_RpcRequest_size                  6275
#define nxp_iot_RpcResponse_size                 6275

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
