/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ServiceDescriptor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nxp_iot_SssObjectReference, nxp_iot_SssObjectReference, AUTO)


PB_BIND(nxp_iot_ServiceDescriptor, nxp_iot_ServiceDescriptor, 2)



