/* Copyright 2022, 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXP_IOT_SERVICEDESCRIPTOR_PB_H_INCLUDED
#define PB_NXP_IOT_SERVICEDESCRIPTOR_PB_H_INCLUDED
#include <pb.h>
#include "Types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _nxp_iot_SssObjectReference {
    bool has_type;
    nxp_iot_EndpointType type;
    bool has_endpoint_id;
    uint32_t endpoint_id;
    bool has_object_id;
    uint32_t object_id;
} nxp_iot_SssObjectReference;

typedef struct _nxp_iot_ServiceDescriptor {
    uint64_t identifier;
    bool has_service_type;
    nxp_iot_ServiceType service_type;
    char *hostname;
    bool has_port;
    uint32_t port;
    bool has_timeout_ms;
    uint32_t timeout_ms;
    bool has_protocol;
    nxp_iot_ServiceProtocolType protocol;
    char *client_id;
    char *username;
    char *password;
    pb_bytes_array_t *client_certificate;
    pb_bytes_array_t *server_certificate;
    pb_callback_t client_key;
    char *customer_metadata_json;
    bool has_client_certificate_sss_ref;
    nxp_iot_SssObjectReference client_certificate_sss_ref;
    bool has_server_certificate_sss_ref;
    nxp_iot_SssObjectReference server_certificate_sss_ref;
    bool has_client_key_sss_ref;
    nxp_iot_SssObjectReference client_key_sss_ref;
    /* AZURE specific: */
    char *azure_id_scope;
    char *azure_registration_id;
    char *azure_global_device_endpoint;
} nxp_iot_ServiceDescriptor;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define nxp_iot_SssObjectReference_init_default  {false, _nxp_iot_EndpointType_MIN, false, 0, false, 0}
#define nxp_iot_ServiceDescriptor_init_default   {0, false, _nxp_iot_ServiceType_MIN, NULL, false, 0, false, 0, false, _nxp_iot_ServiceProtocolType_MIN, NULL, NULL, NULL, NULL, NULL, {{NULL}, NULL}, NULL, false, nxp_iot_SssObjectReference_init_default, false, nxp_iot_SssObjectReference_init_default, false, nxp_iot_SssObjectReference_init_default, NULL, NULL, NULL}
#define nxp_iot_SssObjectReference_init_zero     {false, _nxp_iot_EndpointType_MIN, false, 0, false, 0}
#define nxp_iot_ServiceDescriptor_init_zero      {0, false, _nxp_iot_ServiceType_MIN, NULL, false, 0, false, 0, false, _nxp_iot_ServiceProtocolType_MIN, NULL, NULL, NULL, NULL, NULL, {{NULL}, NULL}, NULL, false, nxp_iot_SssObjectReference_init_zero, false, nxp_iot_SssObjectReference_init_zero, false, nxp_iot_SssObjectReference_init_zero, NULL, NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define nxp_iot_SssObjectReference_type_tag      1
#define nxp_iot_SssObjectReference_endpoint_id_tag 2
#define nxp_iot_SssObjectReference_object_id_tag 3
#define nxp_iot_ServiceDescriptor_identifier_tag 1
#define nxp_iot_ServiceDescriptor_service_type_tag 2
#define nxp_iot_ServiceDescriptor_hostname_tag   10
#define nxp_iot_ServiceDescriptor_port_tag       11
#define nxp_iot_ServiceDescriptor_timeout_ms_tag 12
#define nxp_iot_ServiceDescriptor_protocol_tag   13
#define nxp_iot_ServiceDescriptor_client_id_tag  14
#define nxp_iot_ServiceDescriptor_username_tag   15
#define nxp_iot_ServiceDescriptor_password_tag   16
#define nxp_iot_ServiceDescriptor_client_certificate_tag 20
#define nxp_iot_ServiceDescriptor_server_certificate_tag 21
#define nxp_iot_ServiceDescriptor_client_key_tag 22
#define nxp_iot_ServiceDescriptor_customer_metadata_json_tag 30
#define nxp_iot_ServiceDescriptor_client_certificate_sss_ref_tag 50
#define nxp_iot_ServiceDescriptor_server_certificate_sss_ref_tag 51
#define nxp_iot_ServiceDescriptor_client_key_sss_ref_tag 52
#define nxp_iot_ServiceDescriptor_azure_id_scope_tag 100
#define nxp_iot_ServiceDescriptor_azure_registration_id_tag 101
#define nxp_iot_ServiceDescriptor_azure_global_device_endpoint_tag 102

/* Struct field encoding specification for nanopb */
#define nxp_iot_SssObjectReference_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   endpoint_id,       2) \
X(a, STATIC,   OPTIONAL, UINT32,   object_id,         3)
#define nxp_iot_SssObjectReference_CALLBACK NULL
#define nxp_iot_SssObjectReference_DEFAULT NULL

#define nxp_iot_ServiceDescriptor_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FIXED64,  identifier,        1) \
X(a, STATIC,   OPTIONAL, UENUM,    service_type,      2) \
X(a, POINTER,  OPTIONAL, STRING,   hostname,         10) \
X(a, STATIC,   OPTIONAL, UINT32,   port,             11) \
X(a, STATIC,   OPTIONAL, UINT32,   timeout_ms,       12) \
X(a, STATIC,   OPTIONAL, UENUM,    protocol,         13) \
X(a, POINTER,  OPTIONAL, STRING,   client_id,        14) \
X(a, POINTER,  OPTIONAL, STRING,   username,         15) \
X(a, POINTER,  OPTIONAL, STRING,   password,         16) \
X(a, POINTER,  OPTIONAL, BYTES,    client_certificate,  20) \
X(a, POINTER,  OPTIONAL, BYTES,    server_certificate,  21) \
X(a, CALLBACK, OPTIONAL, BYTES,    client_key,       22) \
X(a, POINTER,  OPTIONAL, STRING,   customer_metadata_json,  30) \
X(a, STATIC,   OPTIONAL, MESSAGE,  client_certificate_sss_ref,  50) \
X(a, STATIC,   OPTIONAL, MESSAGE,  server_certificate_sss_ref,  51) \
X(a, STATIC,   OPTIONAL, MESSAGE,  client_key_sss_ref,  52) \
X(a, POINTER,  OPTIONAL, STRING,   azure_id_scope,  100) \
X(a, POINTER,  OPTIONAL, STRING,   azure_registration_id, 101) \
X(a, POINTER,  OPTIONAL, STRING,   azure_global_device_endpoint, 102)
#define nxp_iot_ServiceDescriptor_CALLBACK pb_default_field_callback
#define nxp_iot_ServiceDescriptor_DEFAULT (const pb_byte_t*)"\x68\x01\x00"
#define nxp_iot_ServiceDescriptor_client_certificate_sss_ref_MSGTYPE nxp_iot_SssObjectReference
#define nxp_iot_ServiceDescriptor_server_certificate_sss_ref_MSGTYPE nxp_iot_SssObjectReference
#define nxp_iot_ServiceDescriptor_client_key_sss_ref_MSGTYPE nxp_iot_SssObjectReference

extern const pb_msgdesc_t nxp_iot_SssObjectReference_msg;
extern const pb_msgdesc_t nxp_iot_ServiceDescriptor_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxp_iot_SssObjectReference_fields &nxp_iot_SssObjectReference_msg
#define nxp_iot_ServiceDescriptor_fields &nxp_iot_ServiceDescriptor_msg

/* Maximum encoded size of messages (where known) */
/* nxp_iot_ServiceDescriptor_size depends on runtime parameters */
#define NXP_IOT_SERVICEDESCRIPTOR_PB_H_MAX_SIZE  nxp_iot_SssObjectReference_size
#define nxp_iot_SssObjectReference_size          14

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
