/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_EVSE_DEFINES_PB_H_INCLUDED
#define PB_EVSE_DEFINES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum proximity_pilot_state {
    PROXIMITY_PILOT_STATE_PROXIMITY_PILOT_UNPLUGGED = 0,
    PROXIMITY_PILOT_STATE_PROXIMITY_PILOT_PLUGGED_NOT_LATCHED = 1,
    PROXIMITY_PILOT_STATE_PROXIMITY_PILOT_PLUGGED_LATCHED = 2
} proximity_pilot_state_t;

typedef enum control_pilot_state {
    CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_A = 0,
    CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_B = 1,
    CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_C = 2,
    CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_D = 3,
    CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_E = 4,
    CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_F = 5
} control_pilot_state_t;

typedef enum control_mode {
    /* EMETER operates standalone only configuration commands accepted */
    CONTROL_MODE_STAND_ALONE_CHARGER = 0,
    /* EMETER does LowLevel Charging and accept commands for HLC */
    CONTROL_MODE_HYBRID_CHARGER = 1,
    /* EMETER does nothing for AC charger */
    CONTROL_MODE_FULL_HOST_CHARGER = 2
} control_mode_t;

typedef enum relay_state {
    RELAY_STATE_RELAY_OPEN = 0,
    RELAY_STATE_RELAY_CLOSED = 1
} relay_state_t;

typedef enum allow_charge {
    ALLOW_CHARGE_INVALID_CHARGE_READINESS = 0,
    ALLOW_CHARGE_CHARGE_ENABLE = 170, /* Ready to charge */
    ALLOW_CHARGE_CHARGE_DISABLE = 85 /* Not ready to charge */
} allow_charge_t;

typedef enum charging_process {
    CHARGING_PROCESS_INVALID_CHARGING_PROCESS = 0,
    CHARGING_PROCESS_START_CHARGE = 1,
    CHARGING_PROCESS_STOP_CHARGE = 2,
    CHARGING_PROCESS_CHARGE_ONGOING = 3,
    CHARGING_PROCESS_CHARGING = 4,
    CHARGING_PROCESS_START_DISCHARGE = 5,
    CHARGING_PROCESS_STOP_DISCHARGE = 7,
    CHARGING_PROCESS_DISCHARGE_ONGOING = 8,
    CHARGING_PROCESS_DISCHARGING = 9,
    CHARGING_PROCESS_IDLE = 10
} charging_process_t;

/* Struct definitions */
typedef struct gfci_state {
    uint32_t gfci_state;
} gfci_state_t;

typedef struct control_pilot_value {
    uint32_t cp_value;
} control_pilot_value_t;

typedef struct pwm_value {
    float pwm_value;
} pwm_value_t;

typedef struct pwm_ms_value {
    uint32_t pwm_value;
} pwm_ms_value_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _PROXIMITY_PILOT_STATE_MIN PROXIMITY_PILOT_STATE_PROXIMITY_PILOT_UNPLUGGED
#define _PROXIMITY_PILOT_STATE_MAX PROXIMITY_PILOT_STATE_PROXIMITY_PILOT_PLUGGED_LATCHED
#define _PROXIMITY_PILOT_STATE_ARRAYSIZE ((proximity_pilot_state_t)(PROXIMITY_PILOT_STATE_PROXIMITY_PILOT_PLUGGED_LATCHED+1))

#define _CONTROL_PILOT_STATE_MIN CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_A
#define _CONTROL_PILOT_STATE_MAX CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_F
#define _CONTROL_PILOT_STATE_ARRAYSIZE ((control_pilot_state_t)(CONTROL_PILOT_STATE_CONTROL_PILOT_STATE_F+1))

#define _CONTROL_MODE_MIN CONTROL_MODE_STAND_ALONE_CHARGER
#define _CONTROL_MODE_MAX CONTROL_MODE_FULL_HOST_CHARGER
#define _CONTROL_MODE_ARRAYSIZE ((control_mode_t)(CONTROL_MODE_FULL_HOST_CHARGER+1))

#define _RELAY_STATE_MIN RELAY_STATE_RELAY_OPEN
#define _RELAY_STATE_MAX RELAY_STATE_RELAY_CLOSED
#define _RELAY_STATE_ARRAYSIZE ((relay_state_t)(RELAY_STATE_RELAY_CLOSED+1))

#define _ALLOW_CHARGE_MIN ALLOW_CHARGE_INVALID_CHARGE_READINESS
#define _ALLOW_CHARGE_MAX ALLOW_CHARGE_CHARGE_ENABLE
#define _ALLOW_CHARGE_ARRAYSIZE ((allow_charge_t)(ALLOW_CHARGE_CHARGE_ENABLE+1))

#define _CHARGING_PROCESS_MIN CHARGING_PROCESS_INVALID_CHARGING_PROCESS
#define _CHARGING_PROCESS_MAX CHARGING_PROCESS_IDLE
#define _CHARGING_PROCESS_ARRAYSIZE ((charging_process_t)(CHARGING_PROCESS_IDLE+1))






/* Initializer values for message structs */
#define GFCI_STATE_INIT_DEFAULT                  {0}
#define CONTROL_PILOT_VALUE_INIT_DEFAULT         {0}
#define PWM_VALUE_INIT_DEFAULT                   {0}
#define PWM_MS_VALUE_INIT_DEFAULT                {0}
#define GFCI_STATE_INIT_ZERO                     {0}
#define CONTROL_PILOT_VALUE_INIT_ZERO            {0}
#define PWM_VALUE_INIT_ZERO                      {0}
#define PWM_MS_VALUE_INIT_ZERO                   {0}

/* Field tags (for use in manual encoding/decoding) */
#define GFCI_STATE_GFCI_STATE_TAG                1
#define CONTROL_PILOT_VALUE_CP_VALUE_TAG         1
#define PWM_VALUE_PWM_VALUE_TAG                  1
#define PWM_MS_VALUE_PWM_VALUE_TAG               1

/* Struct field encoding specification for nanopb */
#define GFCI_STATE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gfci_state,        1)
#define GFCI_STATE_CALLBACK NULL
#define GFCI_STATE_DEFAULT NULL

#define CONTROL_PILOT_VALUE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cp_value,          1)
#define CONTROL_PILOT_VALUE_CALLBACK NULL
#define CONTROL_PILOT_VALUE_DEFAULT NULL

#define PWM_VALUE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pwm_value,         1)
#define PWM_VALUE_CALLBACK NULL
#define PWM_VALUE_DEFAULT NULL

#define PWM_MS_VALUE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pwm_value,         1)
#define PWM_MS_VALUE_CALLBACK NULL
#define PWM_MS_VALUE_DEFAULT NULL

extern const pb_msgdesc_t gfci_state_t_msg;
extern const pb_msgdesc_t control_pilot_value_t_msg;
extern const pb_msgdesc_t pwm_value_t_msg;
extern const pb_msgdesc_t pwm_ms_value_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GFCI_STATE_FIELDS &gfci_state_t_msg
#define CONTROL_PILOT_VALUE_FIELDS &control_pilot_value_t_msg
#define PWM_VALUE_FIELDS &pwm_value_t_msg
#define PWM_MS_VALUE_FIELDS &pwm_ms_value_t_msg

/* Maximum encoded size of messages (where known) */
#define CONTROL_PILOT_VALUE_SIZE                 6
#define EVSE_DEFINES_PB_H_MAX_SIZE               GFCI_STATE_SIZE
#define GFCI_STATE_SIZE                          6
#define PWM_MS_VALUE_SIZE                        6
#define PWM_VALUE_SIZE                           5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
