/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "evse_defines.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GFCI_STATE, gfci_state_t, AUTO)


PB_BIND(CONTROL_PILOT_VALUE, control_pilot_value_t, AUTO)


PB_BIND(PWM_VALUE, pwm_value_t, AUTO)


PB_BIND(PWM_MS_VALUE, pwm_ms_value_t, AUTO)















