/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "message_descriptor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RESPOND, respond_t, 2)


PB_BIND(REQUEST, request_t, 2)


PB_BIND(MESSAGE_METADATA, message_metadata_t, AUTO)


PB_BIND(E_METER_MESSAGE, e_meter_message_t, 2)


PB_BIND(E_METER_MESSAGE_CRC, e_meter_message_crc_t, 2)



