/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGE_DESCRIPTOR_PB_H_INCLUDED
#define PB_MESSAGE_DESCRIPTOR_PB_H_INCLUDED
#include <pb.h>
#include "evse_defines.pb.h"
#include "metrology_defines.pb.h"
#include "types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct respond {
    command_id_t command_id;
    pb_size_t which_respond;
    union {
        /* optional is present only if emeter_respond_status is 0 */
        metrology_schema_t metrology;
        present_voltage_t present_voltage;
        present_current_t present_current;
        present_power_t present_power;
        present_active_power_t present_active_power;
        present_reactive_power_t present_reactive_power;
        present_apparent_power_t present_apparent_power;
        power_direction_t power_direction;
        energy_meter_index_t energy_meter_index;
        proximity_pilot_state_t pp_state;
        control_pilot_state_t cp_state;
        gfci_state_t gfci_state;
        control_pilot_value_t cp_value;
        pwm_value_t pwm_value;
        pwm_ms_value_t pwm_ms_value;
        relay_state_t relay_state;
        sw_version_t sw_version;
        hw_version_t hw_version;
        emeter_timestamp_t timestamp;
        allow_charge_t allow_charge;
        charging_process_t charge_state;
        /* Faults and Limits Commands */
        fault_value_t fault_value;
        power_high_limit_t power_high_limit;
        current_high_limit_t current_high_limit;
        voltage_high_limit_t voltage_high_limit;
        voltage_low_limit_t voltage_low_limit;
        nominal_current_t nominal_current;
        class_b_detailed_faults_t class_b_detailed_faults;
        app_detailed_faults_t app_detailed_faults;
        /* Control Mode and Advertise Commands */
        control_mode_t control_mode;
        advertise_freq_t advertise_freq;
        temperature_t temperature;
        empty_t no_data;
    } respond;
} respond_t;

typedef struct request {
    command_id_t command_id;
    pb_size_t which_request;
    union {
        /* Changed to match Respond values */
        pwm_value_t pwm_value; /* was 0x61 */
        pwm_ms_value_t pwm_ms_value; /* was 0x63 */
        relay_state_t relay_state; /* was 0x65 */
        uint32_t unix_time;
        allow_charge_t allow_charge; /* was 0x81 */
        charging_process_t charge_state; /* was 0x83 */
        power_high_limit_t power_high_limit; /* was 0x92 */
        current_high_limit_t current_high_limit; /* was 0x94 */
        voltage_high_limit_t voltage_high_limit; /* was 0x96 */
        voltage_low_limit_t voltage_low_limit; /* was 0x98 */
        nominal_current_t nominal_current; /* was 0x9A */
        control_mode_t control_mode; /* was 0xA1 */
        advertise_freq_t advertise_freq;
        firmware_update_t firmware_update;
        metrology_schema_t metrology;
        control_pilot_state_t cp_state;
        proximity_pilot_state_t pp_state;
        heartbeat_t heartbeat;
        lpm_state_t lpm_state;
        gfci_state_t gfci_state;
        fault_value_t fault_value;
        empty_t no_data;
    } request;
} request_t;

typedef struct message_metadata {
    bool has_sw_version;
    sw_version_t sw_version;
    bool has_status;
    status_code_t status;
    /* optional uint32 correlation_id = 3 [(nanopb).int_size = IS_16];
    optional uint32 payload_size = 5 [(nanopb).int_size = IS_8]; */
    bool has_correlation_id;
    uint32_t correlation_id;
    bool has_payload_size;
    uint32_t payload_size;
    bool has_device_type;
    device_type_t device_type;
} message_metadata_t;

typedef struct e_meter_message {
    /* uint32 msg_id = 1 [(nanopb).int_size = IS_16]; */
    uint32_t msg_id;
    message_metadata_t metadata;
    pb_size_t which_message_payload;
    union {
        /* Message request done by the host controller */
        request_t request;
        /* Message respond to a host request */
        respond_t respond;
    };
} e_meter_message_t;

typedef struct e_meter_message_crc {
    e_meter_message_t message;
    /* uint32 crc  = 2 [(nanopb).int_size = IS_16]; */
    uint32_t crc;
} e_meter_message_crc_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RESPOND_INIT_DEFAULT                     {_COMMAND_ID_MIN, 0, {METROLOGY_SCHEMA_INIT_DEFAULT}}
#define REQUEST_INIT_DEFAULT                     {_COMMAND_ID_MIN, 0, {PWM_VALUE_INIT_DEFAULT}}
#define MESSAGE_METADATA_INIT_DEFAULT            {false, SW_VERSION_INIT_DEFAULT, false, _STATUS_CODE_MIN, false, 0, false, 0, false, _DEVICE_TYPE_MIN}
#define E_METER_MESSAGE_INIT_DEFAULT             {0, MESSAGE_METADATA_INIT_DEFAULT, 0, {REQUEST_INIT_DEFAULT}}
#define E_METER_MESSAGE_CRC_INIT_DEFAULT         {E_METER_MESSAGE_INIT_DEFAULT, 0}
#define RESPOND_INIT_ZERO                        {_COMMAND_ID_MIN, 0, {METROLOGY_SCHEMA_INIT_ZERO}}
#define REQUEST_INIT_ZERO                        {_COMMAND_ID_MIN, 0, {PWM_VALUE_INIT_ZERO}}
#define MESSAGE_METADATA_INIT_ZERO               {false, SW_VERSION_INIT_ZERO, false, _STATUS_CODE_MIN, false, 0, false, 0, false, _DEVICE_TYPE_MIN}
#define E_METER_MESSAGE_INIT_ZERO                {0, MESSAGE_METADATA_INIT_ZERO, 0, {REQUEST_INIT_ZERO}}
#define E_METER_MESSAGE_CRC_INIT_ZERO            {E_METER_MESSAGE_INIT_ZERO, 0}

/* Field tags (for use in manual encoding/decoding) */
#define RESPOND_COMMAND_ID_TAG                   1
#define RESPOND_METROLOGY_TAG                    48
#define RESPOND_PRESENT_VOLTAGE_TAG              49
#define RESPOND_PRESENT_CURRENT_TAG              50
#define RESPOND_PRESENT_POWER_TAG                51
#define RESPOND_PRESENT_ACTIVE_POWER_TAG         52
#define RESPOND_PRESENT_REACTIVE_POWER_TAG       53
#define RESPOND_PRESENT_APPARENT_POWER_TAG       54
#define RESPOND_POWER_DIRECTION_TAG              55
#define RESPOND_ENERGY_METER_INDEX_TAG           56
#define RESPOND_PP_STATE_TAG                     80
#define RESPOND_CP_STATE_TAG                     81
#define RESPOND_GFCI_STATE_TAG                   82
#define RESPOND_CP_VALUE_TAG                     83
#define RESPOND_PWM_VALUE_TAG                    96
#define RESPOND_PWM_MS_VALUE_TAG                 98
#define RESPOND_RELAY_STATE_TAG                  100
#define RESPOND_SW_VERSION_TAG                   112
#define RESPOND_HW_VERSION_TAG                   113
#define RESPOND_TIMESTAMP_TAG                    114
#define RESPOND_ALLOW_CHARGE_TAG                 128
#define RESPOND_CHARGE_STATE_TAG                 130
#define RESPOND_FAULT_VALUE_TAG                  144
#define RESPOND_POWER_HIGH_LIMIT_TAG             145
#define RESPOND_CURRENT_HIGH_LIMIT_TAG           147
#define RESPOND_VOLTAGE_HIGH_LIMIT_TAG           149
#define RESPOND_VOLTAGE_LOW_LIMIT_TAG            151
#define RESPOND_NOMINAL_CURRENT_TAG              153
#define RESPOND_CLASS_B_DETAILED_FAULTS_TAG      155
#define RESPOND_APP_DETAILED_FAULTS_TAG          156
#define RESPOND_CONTROL_MODE_TAG                 160
#define RESPOND_ADVERTISE_FREQ_TAG               165
#define RESPOND_TEMPERATURE_TAG                  176
#define RESPOND_NO_DATA_TAG                      255
#define REQUEST_COMMAND_ID_TAG                   1
#define REQUEST_PWM_VALUE_TAG                    96
#define REQUEST_PWM_MS_VALUE_TAG                 98
#define REQUEST_RELAY_STATE_TAG                  100
#define REQUEST_UNIX_TIME_TAG                    115
#define REQUEST_ALLOW_CHARGE_TAG                 128
#define REQUEST_CHARGE_STATE_TAG                 130
#define REQUEST_POWER_HIGH_LIMIT_TAG             145
#define REQUEST_CURRENT_HIGH_LIMIT_TAG           147
#define REQUEST_VOLTAGE_HIGH_LIMIT_TAG           149
#define REQUEST_VOLTAGE_LOW_LIMIT_TAG            151
#define REQUEST_NOMINAL_CURRENT_TAG              153
#define REQUEST_CONTROL_MODE_TAG                 160
#define REQUEST_ADVERTISE_FREQ_TAG               165
#define REQUEST_FIRMWARE_UPDATE_TAG              193
#define REQUEST_METROLOGY_TAG                    208
#define REQUEST_CP_STATE_TAG                     209
#define REQUEST_PP_STATE_TAG                     210
#define REQUEST_HEARTBEAT_TAG                    214
#define REQUEST_LPM_STATE_TAG                    215
#define REQUEST_GFCI_STATE_TAG                   216
#define REQUEST_FAULT_VALUE_TAG                  217
#define REQUEST_NO_DATA_TAG                      255
#define MESSAGE_METADATA_SW_VERSION_TAG          1
#define MESSAGE_METADATA_STATUS_TAG              2
#define MESSAGE_METADATA_CORRELATION_ID_TAG      3
#define MESSAGE_METADATA_PAYLOAD_SIZE_TAG        5
#define MESSAGE_METADATA_DEVICE_TYPE_TAG         6
#define E_METER_MESSAGE_MSG_ID_TAG               1
#define E_METER_MESSAGE_METADATA_TAG             2
#define E_METER_MESSAGE_REQUEST_TAG              4
#define E_METER_MESSAGE_RESPOND_TAG              5
#define E_METER_MESSAGE_CRC_MESSAGE_TAG          1
#define E_METER_MESSAGE_CRC_CRC_TAG              2

/* Struct field encoding specification for nanopb */
#define RESPOND_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,metrology,respond.metrology),  48) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,present_voltage,respond.present_voltage),  49) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,present_current,respond.present_current),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,present_power,respond.present_power),  51) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,present_active_power,respond.present_active_power),  52) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,present_reactive_power,respond.present_reactive_power),  53) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,present_apparent_power,respond.present_apparent_power),  54) \
X(a, STATIC,   ONEOF,    UENUM,    (respond,power_direction,respond.power_direction),  55) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,energy_meter_index,respond.energy_meter_index),  56) \
X(a, STATIC,   ONEOF,    UENUM,    (respond,pp_state,respond.pp_state),  80) \
X(a, STATIC,   ONEOF,    UENUM,    (respond,cp_state,respond.cp_state),  81) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,gfci_state,respond.gfci_state),  82) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,cp_value,respond.cp_value),  83) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,pwm_value,respond.pwm_value),  96) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,pwm_ms_value,respond.pwm_ms_value),  98) \
X(a, STATIC,   ONEOF,    UENUM,    (respond,relay_state,respond.relay_state), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,sw_version,respond.sw_version), 112) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,hw_version,respond.hw_version), 113) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,timestamp,respond.timestamp), 114) \
X(a, STATIC,   ONEOF,    UENUM,    (respond,allow_charge,respond.allow_charge), 128) \
X(a, STATIC,   ONEOF,    UENUM,    (respond,charge_state,respond.charge_state), 130) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,fault_value,respond.fault_value), 144) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,power_high_limit,respond.power_high_limit), 145) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,current_high_limit,respond.current_high_limit), 147) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,voltage_high_limit,respond.voltage_high_limit), 149) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,voltage_low_limit,respond.voltage_low_limit), 151) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,nominal_current,respond.nominal_current), 153) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,class_b_detailed_faults,respond.class_b_detailed_faults), 155) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,app_detailed_faults,respond.app_detailed_faults), 156) \
X(a, STATIC,   ONEOF,    UENUM,    (respond,control_mode,respond.control_mode), 160) \
X(a, STATIC,   ONEOF,    UENUM,    (respond,advertise_freq,respond.advertise_freq), 165) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,temperature,respond.temperature), 176) \
X(a, STATIC,   ONEOF,    MESSAGE,  (respond,no_data,respond.no_data), 255)
#define RESPOND_CALLBACK NULL
#define RESPOND_DEFAULT NULL
#define respond_t_respond_metrology_MSGTYPE metrology_schema_t
#define respond_t_respond_present_voltage_MSGTYPE present_voltage_t
#define respond_t_respond_present_current_MSGTYPE present_current_t
#define respond_t_respond_present_power_MSGTYPE present_power_t
#define respond_t_respond_present_active_power_MSGTYPE present_active_power_t
#define respond_t_respond_present_reactive_power_MSGTYPE present_reactive_power_t
#define respond_t_respond_present_apparent_power_MSGTYPE present_apparent_power_t
#define respond_t_respond_energy_meter_index_MSGTYPE energy_meter_index_t
#define respond_t_respond_gfci_state_MSGTYPE gfci_state_t
#define respond_t_respond_cp_value_MSGTYPE control_pilot_value_t
#define respond_t_respond_pwm_value_MSGTYPE pwm_value_t
#define respond_t_respond_pwm_ms_value_MSGTYPE pwm_ms_value_t
#define respond_t_respond_sw_version_MSGTYPE sw_version_t
#define respond_t_respond_hw_version_MSGTYPE hw_version_t
#define respond_t_respond_timestamp_MSGTYPE emeter_timestamp_t
#define respond_t_respond_fault_value_MSGTYPE fault_value_t
#define respond_t_respond_power_high_limit_MSGTYPE power_high_limit_t
#define respond_t_respond_current_high_limit_MSGTYPE current_high_limit_t
#define respond_t_respond_voltage_high_limit_MSGTYPE voltage_high_limit_t
#define respond_t_respond_voltage_low_limit_MSGTYPE voltage_low_limit_t
#define respond_t_respond_nominal_current_MSGTYPE nominal_current_t
#define respond_t_respond_class_b_detailed_faults_MSGTYPE class_b_detailed_faults_t
#define respond_t_respond_app_detailed_faults_MSGTYPE app_detailed_faults_t
#define respond_t_respond_temperature_MSGTYPE temperature_t
#define respond_t_respond_no_data_MSGTYPE empty_t

#define REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,pwm_value,request.pwm_value),  96) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,pwm_ms_value,request.pwm_ms_value),  98) \
X(a, STATIC,   ONEOF,    UENUM,    (request,relay_state,request.relay_state), 100) \
X(a, STATIC,   ONEOF,    UINT32,   (request,unix_time,request.unix_time), 115) \
X(a, STATIC,   ONEOF,    UENUM,    (request,allow_charge,request.allow_charge), 128) \
X(a, STATIC,   ONEOF,    UENUM,    (request,charge_state,request.charge_state), 130) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,power_high_limit,request.power_high_limit), 145) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,current_high_limit,request.current_high_limit), 147) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,voltage_high_limit,request.voltage_high_limit), 149) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,voltage_low_limit,request.voltage_low_limit), 151) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,nominal_current,request.nominal_current), 153) \
X(a, STATIC,   ONEOF,    UENUM,    (request,control_mode,request.control_mode), 160) \
X(a, STATIC,   ONEOF,    UENUM,    (request,advertise_freq,request.advertise_freq), 165) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,firmware_update,request.firmware_update), 193) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,metrology,request.metrology), 208) \
X(a, STATIC,   ONEOF,    UENUM,    (request,cp_state,request.cp_state), 209) \
X(a, STATIC,   ONEOF,    UENUM,    (request,pp_state,request.pp_state), 210) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,heartbeat,request.heartbeat), 214) \
X(a, STATIC,   ONEOF,    UENUM,    (request,lpm_state,request.lpm_state), 215) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,gfci_state,request.gfci_state), 216) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,fault_value,request.fault_value), 217) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,no_data,request.no_data), 255)
#define REQUEST_CALLBACK NULL
#define REQUEST_DEFAULT NULL
#define request_t_request_pwm_value_MSGTYPE pwm_value_t
#define request_t_request_pwm_ms_value_MSGTYPE pwm_ms_value_t
#define request_t_request_power_high_limit_MSGTYPE power_high_limit_t
#define request_t_request_current_high_limit_MSGTYPE current_high_limit_t
#define request_t_request_voltage_high_limit_MSGTYPE voltage_high_limit_t
#define request_t_request_voltage_low_limit_MSGTYPE voltage_low_limit_t
#define request_t_request_nominal_current_MSGTYPE nominal_current_t
#define request_t_request_firmware_update_MSGTYPE firmware_update_t
#define request_t_request_metrology_MSGTYPE metrology_schema_t
#define request_t_request_heartbeat_MSGTYPE heartbeat_t
#define request_t_request_gfci_state_MSGTYPE gfci_state_t
#define request_t_request_fault_value_MSGTYPE fault_value_t
#define request_t_request_no_data_MSGTYPE empty_t

#define MESSAGE_METADATA_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sw_version,        1) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   correlation_id,    3) \
X(a, STATIC,   OPTIONAL, UINT32,   payload_size,      5) \
X(a, STATIC,   OPTIONAL, UENUM,    device_type,       6)
#define MESSAGE_METADATA_CALLBACK NULL
#define MESSAGE_METADATA_DEFAULT NULL
#define message_metadata_t_sw_version_MSGTYPE sw_version_t

#define E_METER_MESSAGE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   msg_id,            1) \
X(a, STATIC,   SINGULAR, MESSAGE,  metadata,          2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_payload,request,request),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message_payload,respond,respond),   5)
#define E_METER_MESSAGE_CALLBACK NULL
#define E_METER_MESSAGE_DEFAULT NULL
#define e_meter_message_t_metadata_MSGTYPE message_metadata_t
#define e_meter_message_t_message_payload_request_MSGTYPE request_t
#define e_meter_message_t_message_payload_respond_MSGTYPE respond_t

#define E_METER_MESSAGE_CRC_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  message,           1) \
X(a, STATIC,   SINGULAR, UINT32,   crc,               2)
#define E_METER_MESSAGE_CRC_CALLBACK NULL
#define E_METER_MESSAGE_CRC_DEFAULT NULL
#define e_meter_message_crc_t_message_MSGTYPE e_meter_message_t

extern const pb_msgdesc_t respond_t_msg;
extern const pb_msgdesc_t request_t_msg;
extern const pb_msgdesc_t message_metadata_t_msg;
extern const pb_msgdesc_t e_meter_message_t_msg;
extern const pb_msgdesc_t e_meter_message_crc_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RESPOND_FIELDS &respond_t_msg
#define REQUEST_FIELDS &request_t_msg
#define MESSAGE_METADATA_FIELDS &message_metadata_t_msg
#define E_METER_MESSAGE_FIELDS &e_meter_message_t_msg
#define E_METER_MESSAGE_CRC_FIELDS &e_meter_message_crc_t_msg

/* Maximum encoded size of messages (where known) */
#define E_METER_MESSAGE_CRC_SIZE                 175
#define E_METER_MESSAGE_SIZE                     166
#define MESSAGE_DESCRIPTOR_PB_H_MAX_SIZE         E_METER_MESSAGE_CRC_SIZE
#define MESSAGE_METADATA_SIZE                    36
#define REQUEST_SIZE                             120
#define RESPOND_SIZE                             120

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
