/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_METROLOGY_DEFINES_PB_H_INCLUDED
#define PB_METROLOGY_DEFINES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum power_direction {
    POWER_DIRECTION_GRID2_VEHICLE = 0,
    POWER_DIRECTION_VEHICLE2_GRID = 255
} power_direction_t;

/* Struct definitions */
typedef struct metrology_values {
    bool has_data_phase1;
    float data_phase1;
    bool has_data_phase2;
    float data_phase2;
    bool has_data_phase3;
    float data_phase3;
} metrology_values_t;

typedef struct present_voltage {
    bool has_data;
    metrology_values_t data;
} present_voltage_t;

typedef struct present_current {
    bool has_data;
    metrology_values_t data;
} present_current_t;

typedef struct present_active_power {
    bool has_data;
    metrology_values_t data;
} present_active_power_t;

typedef struct present_reactive_power {
    bool has_data;
    metrology_values_t data;
} present_reactive_power_t;

typedef struct present_apparent_power {
    bool has_data;
    metrology_values_t data;
} present_apparent_power_t;

typedef struct present_power {
    bool has_active_power;
    present_active_power_t active_power;
    bool has_reactive_power;
    present_reactive_power_t reactive_power;
    bool has_apparent_power;
    present_apparent_power_t apparent_power;
} present_power_t;

typedef struct energy_meter_index {
    uint32_t wh_t;
    uint32_t varh_t;
} energy_meter_index_t;

typedef struct metrology_schema {
    bool has_current;
    present_current_t current;
    bool has_voltage;
    present_voltage_t voltage;
    bool has_power;
    present_power_t power;
    /* optional PowerDirection power_direction = 6 [(nanopb).int_size = IS_8]; */
    bool has_power_direction;
    power_direction_t power_direction;
    bool has_energy_meter_index;
    energy_meter_index_t energy_meter_index;
} metrology_schema_t;

typedef struct power_high_limit {
    bool has_data;
    metrology_values_t data;
} power_high_limit_t;

typedef struct current_high_limit {
    bool has_data;
    metrology_values_t data;
} current_high_limit_t;

typedef struct voltage_high_limit {
    bool has_data;
    metrology_values_t data;
} voltage_high_limit_t;

typedef struct voltage_low_limit {
    bool has_data;
    metrology_values_t data;
} voltage_low_limit_t;

typedef struct nominal_current {
    bool has_data;
    metrology_values_t data;
} nominal_current_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _POWER_DIRECTION_MIN POWER_DIRECTION_GRID2_VEHICLE
#define _POWER_DIRECTION_MAX POWER_DIRECTION_VEHICLE2_GRID
#define _POWER_DIRECTION_ARRAYSIZE ((power_direction_t)(POWER_DIRECTION_VEHICLE2_GRID+1))








#define metrology_schema_t_power_direction_ENUMTYPE power_direction_t








/* Initializer values for message structs */
#define METROLOGY_VALUES_INIT_DEFAULT            {false, 0, false, 0, false, 0}
#define PRESENT_VOLTAGE_INIT_DEFAULT             {false, METROLOGY_VALUES_INIT_DEFAULT}
#define PRESENT_CURRENT_INIT_DEFAULT             {false, METROLOGY_VALUES_INIT_DEFAULT}
#define PRESENT_ACTIVE_POWER_INIT_DEFAULT        {false, METROLOGY_VALUES_INIT_DEFAULT}
#define PRESENT_REACTIVE_POWER_INIT_DEFAULT      {false, METROLOGY_VALUES_INIT_DEFAULT}
#define PRESENT_APPARENT_POWER_INIT_DEFAULT      {false, METROLOGY_VALUES_INIT_DEFAULT}
#define PRESENT_POWER_INIT_DEFAULT               {false, PRESENT_ACTIVE_POWER_INIT_DEFAULT, false, PRESENT_REACTIVE_POWER_INIT_DEFAULT, false, PRESENT_APPARENT_POWER_INIT_DEFAULT}
#define METROLOGY_SCHEMA_INIT_DEFAULT            {false, PRESENT_CURRENT_INIT_DEFAULT, false, PRESENT_VOLTAGE_INIT_DEFAULT, false, PRESENT_POWER_INIT_DEFAULT, false, _POWER_DIRECTION_MIN, false, ENERGY_METER_INDEX_INIT_DEFAULT}
#define ENERGY_METER_INDEX_INIT_DEFAULT          {0, 0}
#define POWER_HIGH_LIMIT_INIT_DEFAULT            {false, METROLOGY_VALUES_INIT_DEFAULT}
#define CURRENT_HIGH_LIMIT_INIT_DEFAULT          {false, METROLOGY_VALUES_INIT_DEFAULT}
#define VOLTAGE_HIGH_LIMIT_INIT_DEFAULT          {false, METROLOGY_VALUES_INIT_DEFAULT}
#define VOLTAGE_LOW_LIMIT_INIT_DEFAULT           {false, METROLOGY_VALUES_INIT_DEFAULT}
#define NOMINAL_CURRENT_INIT_DEFAULT             {false, METROLOGY_VALUES_INIT_DEFAULT}
#define METROLOGY_VALUES_INIT_ZERO               {false, 0, false, 0, false, 0}
#define PRESENT_VOLTAGE_INIT_ZERO                {false, METROLOGY_VALUES_INIT_ZERO}
#define PRESENT_CURRENT_INIT_ZERO                {false, METROLOGY_VALUES_INIT_ZERO}
#define PRESENT_ACTIVE_POWER_INIT_ZERO           {false, METROLOGY_VALUES_INIT_ZERO}
#define PRESENT_REACTIVE_POWER_INIT_ZERO         {false, METROLOGY_VALUES_INIT_ZERO}
#define PRESENT_APPARENT_POWER_INIT_ZERO         {false, METROLOGY_VALUES_INIT_ZERO}
#define PRESENT_POWER_INIT_ZERO                  {false, PRESENT_ACTIVE_POWER_INIT_ZERO, false, PRESENT_REACTIVE_POWER_INIT_ZERO, false, PRESENT_APPARENT_POWER_INIT_ZERO}
#define METROLOGY_SCHEMA_INIT_ZERO               {false, PRESENT_CURRENT_INIT_ZERO, false, PRESENT_VOLTAGE_INIT_ZERO, false, PRESENT_POWER_INIT_ZERO, false, _POWER_DIRECTION_MIN, false, ENERGY_METER_INDEX_INIT_ZERO}
#define ENERGY_METER_INDEX_INIT_ZERO             {0, 0}
#define POWER_HIGH_LIMIT_INIT_ZERO               {false, METROLOGY_VALUES_INIT_ZERO}
#define CURRENT_HIGH_LIMIT_INIT_ZERO             {false, METROLOGY_VALUES_INIT_ZERO}
#define VOLTAGE_HIGH_LIMIT_INIT_ZERO             {false, METROLOGY_VALUES_INIT_ZERO}
#define VOLTAGE_LOW_LIMIT_INIT_ZERO              {false, METROLOGY_VALUES_INIT_ZERO}
#define NOMINAL_CURRENT_INIT_ZERO                {false, METROLOGY_VALUES_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define METROLOGY_VALUES_DATA_PHASE1_TAG         1
#define METROLOGY_VALUES_DATA_PHASE2_TAG         2
#define METROLOGY_VALUES_DATA_PHASE3_TAG         3
#define PRESENT_VOLTAGE_DATA_TAG                 1
#define PRESENT_CURRENT_DATA_TAG                 1
#define PRESENT_ACTIVE_POWER_DATA_TAG            1
#define PRESENT_REACTIVE_POWER_DATA_TAG          1
#define PRESENT_APPARENT_POWER_DATA_TAG          1
#define PRESENT_POWER_ACTIVE_POWER_TAG           1
#define PRESENT_POWER_REACTIVE_POWER_TAG         2
#define PRESENT_POWER_APPARENT_POWER_TAG         3
#define ENERGY_METER_INDEX_WH_T_TAG              1
#define ENERGY_METER_INDEX_VARH_T_TAG            2
#define METROLOGY_SCHEMA_CURRENT_TAG             1
#define METROLOGY_SCHEMA_VOLTAGE_TAG             2
#define METROLOGY_SCHEMA_POWER_TAG               3
#define METROLOGY_SCHEMA_POWER_DIRECTION_TAG     6
#define METROLOGY_SCHEMA_ENERGY_METER_INDEX_TAG  7
#define POWER_HIGH_LIMIT_DATA_TAG                1
#define CURRENT_HIGH_LIMIT_DATA_TAG              1
#define VOLTAGE_HIGH_LIMIT_DATA_TAG              1
#define VOLTAGE_LOW_LIMIT_DATA_TAG               1
#define NOMINAL_CURRENT_DATA_TAG                 1

/* Struct field encoding specification for nanopb */
#define METROLOGY_VALUES_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    data_phase1,       1) \
X(a, STATIC,   OPTIONAL, FLOAT,    data_phase2,       2) \
X(a, STATIC,   OPTIONAL, FLOAT,    data_phase3,       3)
#define METROLOGY_VALUES_CALLBACK NULL
#define METROLOGY_VALUES_DEFAULT NULL

#define PRESENT_VOLTAGE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define PRESENT_VOLTAGE_CALLBACK NULL
#define PRESENT_VOLTAGE_DEFAULT NULL
#define present_voltage_t_data_MSGTYPE metrology_values_t

#define PRESENT_CURRENT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define PRESENT_CURRENT_CALLBACK NULL
#define PRESENT_CURRENT_DEFAULT NULL
#define present_current_t_data_MSGTYPE metrology_values_t

#define PRESENT_ACTIVE_POWER_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define PRESENT_ACTIVE_POWER_CALLBACK NULL
#define PRESENT_ACTIVE_POWER_DEFAULT NULL
#define present_active_power_t_data_MSGTYPE metrology_values_t

#define PRESENT_REACTIVE_POWER_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define PRESENT_REACTIVE_POWER_CALLBACK NULL
#define PRESENT_REACTIVE_POWER_DEFAULT NULL
#define present_reactive_power_t_data_MSGTYPE metrology_values_t

#define PRESENT_APPARENT_POWER_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define PRESENT_APPARENT_POWER_CALLBACK NULL
#define PRESENT_APPARENT_POWER_DEFAULT NULL
#define present_apparent_power_t_data_MSGTYPE metrology_values_t

#define PRESENT_POWER_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_power,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  reactive_power,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  apparent_power,    3)
#define PRESENT_POWER_CALLBACK NULL
#define PRESENT_POWER_DEFAULT NULL
#define present_power_t_active_power_MSGTYPE present_active_power_t
#define present_power_t_reactive_power_MSGTYPE present_reactive_power_t
#define present_power_t_apparent_power_MSGTYPE present_apparent_power_t

#define METROLOGY_SCHEMA_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  current,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  voltage,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  power,             3) \
X(a, STATIC,   OPTIONAL, UENUM,    power_direction,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  energy_meter_index,   7)
#define METROLOGY_SCHEMA_CALLBACK NULL
#define METROLOGY_SCHEMA_DEFAULT NULL
#define metrology_schema_t_current_MSGTYPE present_current_t
#define metrology_schema_t_voltage_MSGTYPE present_voltage_t
#define metrology_schema_t_power_MSGTYPE present_power_t
#define metrology_schema_t_energy_meter_index_MSGTYPE energy_meter_index_t

#define ENERGY_METER_INDEX_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   wh_t,              1) \
X(a, STATIC,   SINGULAR, UINT32,   varh_t,            2)
#define ENERGY_METER_INDEX_CALLBACK NULL
#define ENERGY_METER_INDEX_DEFAULT NULL

#define POWER_HIGH_LIMIT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define POWER_HIGH_LIMIT_CALLBACK NULL
#define POWER_HIGH_LIMIT_DEFAULT NULL
#define power_high_limit_t_data_MSGTYPE metrology_values_t

#define CURRENT_HIGH_LIMIT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define CURRENT_HIGH_LIMIT_CALLBACK NULL
#define CURRENT_HIGH_LIMIT_DEFAULT NULL
#define current_high_limit_t_data_MSGTYPE metrology_values_t

#define VOLTAGE_HIGH_LIMIT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define VOLTAGE_HIGH_LIMIT_CALLBACK NULL
#define VOLTAGE_HIGH_LIMIT_DEFAULT NULL
#define voltage_high_limit_t_data_MSGTYPE metrology_values_t

#define VOLTAGE_LOW_LIMIT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define VOLTAGE_LOW_LIMIT_CALLBACK NULL
#define VOLTAGE_LOW_LIMIT_DEFAULT NULL
#define voltage_low_limit_t_data_MSGTYPE metrology_values_t

#define NOMINAL_CURRENT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define NOMINAL_CURRENT_CALLBACK NULL
#define NOMINAL_CURRENT_DEFAULT NULL
#define nominal_current_t_data_MSGTYPE metrology_values_t

extern const pb_msgdesc_t metrology_values_t_msg;
extern const pb_msgdesc_t present_voltage_t_msg;
extern const pb_msgdesc_t present_current_t_msg;
extern const pb_msgdesc_t present_active_power_t_msg;
extern const pb_msgdesc_t present_reactive_power_t_msg;
extern const pb_msgdesc_t present_apparent_power_t_msg;
extern const pb_msgdesc_t present_power_t_msg;
extern const pb_msgdesc_t metrology_schema_t_msg;
extern const pb_msgdesc_t energy_meter_index_t_msg;
extern const pb_msgdesc_t power_high_limit_t_msg;
extern const pb_msgdesc_t current_high_limit_t_msg;
extern const pb_msgdesc_t voltage_high_limit_t_msg;
extern const pb_msgdesc_t voltage_low_limit_t_msg;
extern const pb_msgdesc_t nominal_current_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define METROLOGY_VALUES_FIELDS &metrology_values_t_msg
#define PRESENT_VOLTAGE_FIELDS &present_voltage_t_msg
#define PRESENT_CURRENT_FIELDS &present_current_t_msg
#define PRESENT_ACTIVE_POWER_FIELDS &present_active_power_t_msg
#define PRESENT_REACTIVE_POWER_FIELDS &present_reactive_power_t_msg
#define PRESENT_APPARENT_POWER_FIELDS &present_apparent_power_t_msg
#define PRESENT_POWER_FIELDS &present_power_t_msg
#define METROLOGY_SCHEMA_FIELDS &metrology_schema_t_msg
#define ENERGY_METER_INDEX_FIELDS &energy_meter_index_t_msg
#define POWER_HIGH_LIMIT_FIELDS &power_high_limit_t_msg
#define CURRENT_HIGH_LIMIT_FIELDS &current_high_limit_t_msg
#define VOLTAGE_HIGH_LIMIT_FIELDS &voltage_high_limit_t_msg
#define VOLTAGE_LOW_LIMIT_FIELDS &voltage_low_limit_t_msg
#define NOMINAL_CURRENT_FIELDS &nominal_current_t_msg

/* Maximum encoded size of messages (where known) */
#define CURRENT_HIGH_LIMIT_SIZE                  17
#define ENERGY_METER_INDEX_SIZE                  12
#define METROLOGY_DEFINES_PB_H_MAX_SIZE          METROLOGY_SCHEMA_SIZE
#define METROLOGY_SCHEMA_SIZE                    114
#define METROLOGY_VALUES_SIZE                    15
#define NOMINAL_CURRENT_SIZE                     17
#define POWER_HIGH_LIMIT_SIZE                    17
#define PRESENT_ACTIVE_POWER_SIZE                17
#define PRESENT_APPARENT_POWER_SIZE              17
#define PRESENT_CURRENT_SIZE                     17
#define PRESENT_POWER_SIZE                       57
#define PRESENT_REACTIVE_POWER_SIZE              17
#define PRESENT_VOLTAGE_SIZE                     17
#define VOLTAGE_HIGH_LIMIT_SIZE                  17
#define VOLTAGE_LOW_LIMIT_SIZE                   17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
