/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "metrology_defines.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(METROLOGY_VALUES, metrology_values_t, AUTO)


PB_BIND(PRESENT_VOLTAGE, present_voltage_t, AUTO)


PB_BIND(PRESENT_CURRENT, present_current_t, AUTO)


PB_BIND(PRESENT_ACTIVE_POWER, present_active_power_t, AUTO)


PB_BIND(PRESENT_REACTIVE_POWER, present_reactive_power_t, AUTO)


PB_BIND(PRESENT_APPARENT_POWER, present_apparent_power_t, AUTO)


PB_BIND(PRESENT_POWER, present_power_t, AUTO)


PB_BIND(METROLOGY_SCHEMA, metrology_schema_t, AUTO)


PB_BIND(ENERGY_METER_INDEX, energy_meter_index_t, AUTO)


PB_BIND(POWER_HIGH_LIMIT, power_high_limit_t, AUTO)


PB_BIND(CURRENT_HIGH_LIMIT, current_high_limit_t, AUTO)


PB_BIND(VOLTAGE_HIGH_LIMIT, voltage_high_limit_t, AUTO)


PB_BIND(VOLTAGE_LOW_LIMIT, voltage_low_limit_t, AUTO)


PB_BIND(NOMINAL_CURRENT, nominal_current_t, AUTO)





