/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TYPES_PB_H_INCLUDED
#define PB_TYPES_PB_H_INCLUDED
#include <pb.h>
#include "evse_defines.pb.h"
#include "metrology_defines.pb.h"


#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum status_code {
    STATUS_CODE_OK = 0,
    STATUS_CODE_ERROR = 1,
    STATUS_CODE_INVALID_DATA = 2,
    STATUS_CODE_NOT_IMPLEMENTED = 3
} status_code_t;

typedef enum command_id {
    /* Invalid Command */
    COMMAND_ID_INVALID_COMMAND = 0, /* Default invalid command */
    /* Async request Host -> Emeter
 All Get message have Empty data
 Metrology Commands */
    COMMAND_ID_GET_METROLOGY_ALL = 48,
    COMMAND_ID_GET_PRESENT_VOLTAGE = 49,
    COMMAND_ID_GET_PRESENT_CURRENT = 50,
    COMMAND_ID_GET_PRESENT_POWER = 51,
    COMMAND_ID_GET_PRESENT_ACTIVE_POWER = 52,
    COMMAND_ID_GET_PRESENT_REACTIVE_POWER = 53,
    COMMAND_ID_GET_PRESENT_APPARENT_POWER = 54,
    COMMAND_ID_GET_POWER_DIRECTION = 55,
    COMMAND_ID_GET_ENERGY_INDEX = 56,
    COMMAND_ID_GET_METROLOGY_LAST = 79,
    /* State Commands */
    COMMAND_ID_GET_PP_STATE = 80,
    COMMAND_ID_GET_CP_STATE = 81,
    COMMAND_ID_GET_GFCI_STATE = 82,
    COMMAND_ID_GET_CP_VALUE = 83,
    /* PWM and Relay Commands */
    COMMAND_ID_GET_PWM = 96,
    COMMAND_ID_SET_PWM = 97,
    COMMAND_ID_GET_PWM_MS = 98,
    COMMAND_ID_SET_PWM_MS = 99,
    COMMAND_ID_GET_RELAY_STATE = 100,
    COMMAND_ID_SET_RELAY_STATE = 101,
    /* Version Commands */
    COMMAND_ID_GET_SW_VERSION = 112,
    COMMAND_ID_GET_HW_VERSION = 113,
    COMMAND_ID_GET_TIMESTAMP = 114,
    COMMAND_ID_SET_TIMESTAMP = 115,
    /* Enable/Charge Commands */
    COMMAND_ID_GET_ALLOW_CHARGE = 128,
    COMMAND_ID_SET_ALLOW_CHARGE = 129, /* This message is ignored if EMETER is in fault state */
    COMMAND_ID_GET_CHARGE_STATE = 130,
    COMMAND_ID_SET_CHARGE_STATE = 131, /* Used in Hybrid_Charger or FullHost_Charger control mode. This message is ignored if EMETER is in fault state */
    /* Faults and Limits Commands */
    COMMAND_ID_GET_FAULT_VALUE = 144,
    COMMAND_ID_GET_POWER_HIGH_LIMIT = 145,
    COMMAND_ID_SET_POWER_HIGH_LIMIT = 146,
    COMMAND_ID_GET_CURRENT_HIGH_LIMIT = 147,
    COMMAND_ID_SET_CURRENT_HIGH_LIMIT = 148,
    COMMAND_ID_GET_VOLTAGE_HIGH_LIMIT = 149,
    COMMAND_ID_SET_VOLTAGE_HIGH_LIMIT = 150,
    COMMAND_ID_GET_VOLTAGE_LOW_LIMIT = 151,
    COMMAND_ID_SET_VOLTAGE_LOW_LIMIT = 152,
    COMMAND_ID_GET_NOMINAL_CURRENT = 153,
    COMMAND_ID_SET_NOMINAL_CURRENT = 154,
    COMMAND_ID_GET_FAULT_DETAILED_CLASS_B = 155,
    COMMAND_ID_GET_FAULT_DETAILED_APP = 156,
    COMMAND_ID_SET_CLEAR_FAULTS = 157, /* THis command is mostly for demo purposes. Clearing the faults should be done in a supervise manner */
    /* Control Mode and Advertise Commands */
    COMMAND_ID_GET_CONTROL_MODE = 160,
    COMMAND_ID_SET_CONTROL_MODE = 161,
    COMMAND_ID_GET_ENABLE_ADVERTISE = 162,
    COMMAND_ID_SET_ENABLE_ADVERTISE = 163,
    COMMAND_ID_GET_ADVERTISE_FREQ = 164,
    COMMAND_ID_SET_ADVERTISE_FREQ = 165,
    /* Temperature Commands */
    COMMAND_ID_GET_TEMPERATURE = 176,
    /* System Commands */
    COMMAND_ID_RESET = 192,
    COMMAND_ID_FIRMWARE_UPDATE = 193,
    COMMAND_ID_FIRMWARE_DOWNLOAD = 194, /* Firmware FIRMWARE_DOWNLOAD command needs to be issued after FIRMWARE_UPDATE command */
    /* Async request Emeter -> Host */
    COMMAND_ID_SET_METROLOGY_ALL = 208,
    COMMAND_ID_SET_CP_STATE = 209,
    COMMAND_ID_SET_PP_STATE = 210,
    COMMAND_ID_SET_CAR_PLUGGED_IN = 211,
    COMMAND_ID_SET_CAR_REMOVED = 212,
    COMMAND_ID_SET_CAR_POWER_REQUEST = 213,
    COMMAND_ID_SET_HEARTBEAT = 214,
    COMMAND_ID_SET_ENTER_LPM = 215,
    COMMAND_ID_SET_GFCI = 216,
    COMMAND_ID_SET_FAULT_VALUE = 217,
    COMMAND_ID_SET_BOOT_COMPLET = 218,
    COMMAND_ID_SET_EMERGENCY_PRESSED = 222
} command_id_t;

typedef enum class_b_fault_type {
    CLASS_B_FAULT_TYPE_CLASSB_NO_FAULT = 0,
    CLASS_B_FAULT_TYPE_CPU_TEST = 1,
    CLASS_B_FAULT_TYPE_FLASH_TEST = 2,
    CLASS_B_FAULT_TYPE_RAM_TEST = 3,
    CLASS_B_FAULT_TYPE_STACK_TEST = 4,
    CLASS_B_FAULT_TYPE_CLOCK_TEST = 5,
    CLASS_B_FAULT_TYPE_PC_TEST = 6,
    CLASS_B_FAULT_TYPE_CPU_PRIMASK = 7,
    CLASS_B_FAULT_TYPE_CPU_REGISTERS = 8,
    CLASS_B_FAULT_TYPE_CPU_NONSTACKED = 9,
    CLASS_B_FAULT_TYPE_CPU_CONTROL = 10,
    CLASS_B_FAULT_TYPE_CPU_SPECIAL = 11,
    CLASS_B_FAULT_TYPE_CPU_FLOAT = 12,
    CLASS_B_FAULT_TYPE_ADC_FIFO = 13,
    CLASS_B_FAULT_TYPE_ADC_BAND = 14,
    CLASS_B_FAULT_TYPE_ADC_RED = 15,
    CLASS_B_FAULT_TYPE_WDOG_TEST = 16,
    CLASS_B_FAULT_TYPE_CLOCK_FI = 17,
    CLASS_B_FAULT_TYPE_INTM_CTIM = 18,
    CLASS_B_FAULT_TYPE_INTM_ADC = 19,
    CLASS_B_FAULT_TYPE_ECC = 20,
    CLASS_B_FAULT_TYPE_MAIN_FLOW = 21,
    CLASS_B_FAULT_TYPE_FAST_FLOW = 22,
    CLASS_B_FAULT_TYPE_SLOW_FLOW = 23,
    CLASS_B_FAULT_TYPE_ISR_TIMING = 24,
    CLASS_B_FAULT_TYPE_PWM_FI = 25,
    CLASS_B_FAULT_TYPE_HEARTBEAT = 26,
    CLASS_B_FAULT_TYPE_GFCI = 27,
    CLASS_B_FAULT_TYPE_RESET_FAULT = 28,
    CLASS_B_FAULT_TYPE_FS_APP = 29
} class_b_fault_type_t;

typedef enum app_fault_type {
    APP_FAULT_TYPE_APP_NO_FAULT = 0,
    APP_FAULT_TYPE_OVERCURRENT_PH1 = 1,
    APP_FAULT_TYPE_OVERCURRENT_PH2 = 2,
    APP_FAULT_TYPE_OVERCURRENT_PH3 = 3,
    APP_FAULT_TYPE_THD = 4,
    APP_FAULT_TYPE_OVERVOLTAGE_PH1 = 5,
    APP_FAULT_TYPE_OVERVOLTAGE_PH2 = 6,
    APP_FAULT_TYPE_OVERVOLTAGE_PH3 = 7,
    APP_FAULT_TYPE_CMP = 8,
    APP_FAULT_TYPE_UNDERVOLTAGE_PH1 = 9,
    APP_FAULT_TYPE_UNDERVOLTAGE_PH2 = 10,
    APP_FAULT_TYPE_UNDERVOLTAGE_PH3 = 11,
    APP_FAULT_TYPE_EMSTOP = 12,
    APP_FAULT_TYPE_TEMP = 13,
    APP_FAULT_TYPE_MIRROR = 14,
    APP_FAULT_TYPE_RELAY_12_V = 15,
    APP_FAULT_TYPE_CLASS_B = 16,
    APP_FAULT_TYPE_GFCI_APP = 17,
    APP_FAULT_TYPE_TEMP_COM = 18
} app_fault_type_t;

typedef enum message_direction {
    MESSAGE_DIRECTION_UNKNOWN = 0,
    MESSAGE_DIRECTION_REQUEST = 1,
    MESSAGE_DIRECTION_RESPONSE = 2
} message_direction_t;

typedef enum advertise_freq {
    ADVERTISE_FREQ_ADVERTISE_FREQ_DISABLE = 0,
    ADVERTISE_FREQ_ADVERTISE_FREQ_1S = 1,
    ADVERTISE_FREQ_ADVERTISE_FREQ_2S = 2,
    ADVERTISE_FREQ_ADVERTISE_FREQ_4S = 4,
    ADVERTISE_FREQ_ADVERTISE_FREQ_8S = 8
} advertise_freq_t;

typedef enum lpm_state {
    LPM_STATE_EXIT_LPM = 0,
    LPM_STATE_ENTER_LPM = 255
} lpm_state_t;

typedef enum device_type {
    DEVICE_TYPE_DEVICE_NOT_SET = 0,
    DEVICE_TYPE_DEVICE_HOST_CONTROLLER = 1,
    DEVICE_TYPE_DEVICE_EMETER = 2,
    DEVICE_TYPE_DEVICE_MAX = 10
} device_type_t;

/* Struct definitions */
typedef struct class_b_detailed_faults {
    pb_size_t faults_count;
    class_b_fault_type_t faults[32];
} class_b_detailed_faults_t;

typedef struct app_detailed_faults {
    pb_size_t faults_count;
    app_fault_type_t faults[32];
} app_detailed_faults_t;

typedef struct sw_version {
    /* uint32 major = 1 [(nanopb).int_size = IS_16];
    uint32 minor = 2 [(nanopb).int_size = IS_16];
    uint32 hotfix = 3 [(nanopb).int_size = IS_16]; */
    uint32_t major;
    uint32_t minor;
    uint32_t hotfix;
} sw_version_t;

typedef struct hw_version {
    /* uint32 version = 1 [(nanopb).int_size = IS_16]; */
    uint32_t version;
} hw_version_t;

typedef struct fault_value {
    uint32_t class_b_fault;
    uint32_t app_fault;
} fault_value_t;

typedef struct firmware_update {
    bool has_fw_version;
    sw_version_t fw_version;
    uint32_t image_size;
} firmware_update_t;

typedef struct firmware_download {
    uint32_t image_offset;
    /* uint32 packetID = 2 [(nanopb).int_size = IS_16];
  repeated uint32 image = 3 [(nanopb).int_size = IS_8, (nanopb).max_count = 246]; */
    uint32_t packet_id;
    pb_callback_t image;
} firmware_download_t;

typedef struct emeter_timestamp {
    uint32_t unix_time;
    uint32_t boot_time;
} emeter_timestamp_t;

typedef struct heartbeat {
    bool has_fault_value;
    fault_value_t fault_value;
} heartbeat_t;

typedef struct temperature {
    float tmp;
} temperature_t;

typedef struct empty {
    char dummy_field;
} empty_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _STATUS_CODE_MIN STATUS_CODE_OK
#define _STATUS_CODE_MAX STATUS_CODE_NOT_IMPLEMENTED
#define _STATUS_CODE_ARRAYSIZE ((status_code_t)(STATUS_CODE_NOT_IMPLEMENTED+1))

#define _COMMAND_ID_MIN COMMAND_ID_INVALID_COMMAND
#define _COMMAND_ID_MAX COMMAND_ID_SET_EMERGENCY_PRESSED
#define _COMMAND_ID_ARRAYSIZE ((command_id_t)(COMMAND_ID_SET_EMERGENCY_PRESSED+1))

#define _CLASS_B_FAULT_TYPE_MIN CLASS_B_FAULT_TYPE_CLASSB_NO_FAULT
#define _CLASS_B_FAULT_TYPE_MAX CLASS_B_FAULT_TYPE_FS_APP
#define _CLASS_B_FAULT_TYPE_ARRAYSIZE ((class_b_fault_type_t)(CLASS_B_FAULT_TYPE_FS_APP+1))

#define _APP_FAULT_TYPE_MIN APP_FAULT_TYPE_APP_NO_FAULT
#define _APP_FAULT_TYPE_MAX APP_FAULT_TYPE_TEMP_COM
#define _APP_FAULT_TYPE_ARRAYSIZE ((app_fault_type_t)(APP_FAULT_TYPE_TEMP_COM+1))

#define _MESSAGE_DIRECTION_MIN MESSAGE_DIRECTION_UNKNOWN
#define _MESSAGE_DIRECTION_MAX MESSAGE_DIRECTION_RESPONSE
#define _MESSAGE_DIRECTION_ARRAYSIZE ((message_direction_t)(MESSAGE_DIRECTION_RESPONSE+1))

#define _ADVERTISE_FREQ_MIN ADVERTISE_FREQ_ADVERTISE_FREQ_DISABLE
#define _ADVERTISE_FREQ_MAX ADVERTISE_FREQ_ADVERTISE_FREQ_8S
#define _ADVERTISE_FREQ_ARRAYSIZE ((advertise_freq_t)(ADVERTISE_FREQ_ADVERTISE_FREQ_8S+1))

#define _LPM_STATE_MIN LPM_STATE_EXIT_LPM
#define _LPM_STATE_MAX LPM_STATE_ENTER_LPM
#define _LPM_STATE_ARRAYSIZE ((lpm_state_t)(LPM_STATE_ENTER_LPM+1))

#define _DEVICE_TYPE_MIN DEVICE_TYPE_DEVICE_NOT_SET
#define _DEVICE_TYPE_MAX DEVICE_TYPE_DEVICE_MAX
#define _DEVICE_TYPE_ARRAYSIZE ((device_type_t)(DEVICE_TYPE_DEVICE_MAX+1))

#define class_b_detailed_faults_t_faults_ENUMTYPE class_b_fault_type_t

#define app_detailed_faults_t_faults_ENUMTYPE app_fault_type_t











/* Initializer values for message structs */
#define CLASS_B_DETAILED_FAULTS_INIT_DEFAULT     {0, {_CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN}}
#define APP_DETAILED_FAULTS_INIT_DEFAULT         {0, {_APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN}}
#define SW_VERSION_INIT_DEFAULT                  {0, 0, 0}
#define HW_VERSION_INIT_DEFAULT                  {0}
#define FAULT_VALUE_INIT_DEFAULT                 {0, 0}
#define FIRMWARE_UPDATE_INIT_DEFAULT             {false, SW_VERSION_INIT_DEFAULT, 0}
#define FIRMWARE_DOWNLOAD_INIT_DEFAULT           {0, 0, {{NULL}, NULL}}
#define EMETER_TIMESTAMP_INIT_DEFAULT            {0, 0}
#define HEARTBEAT_INIT_DEFAULT                   {false, FAULT_VALUE_INIT_DEFAULT}
#define TEMPERATURE_INIT_DEFAULT                 {0}
#define EMPTY_INIT_DEFAULT                       {0}
#define CLASS_B_DETAILED_FAULTS_INIT_ZERO        {0, {_CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN, _CLASS_B_FAULT_TYPE_MIN}}
#define APP_DETAILED_FAULTS_INIT_ZERO            {0, {_APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN, _APP_FAULT_TYPE_MIN}}
#define SW_VERSION_INIT_ZERO                     {0, 0, 0}
#define HW_VERSION_INIT_ZERO                     {0}
#define FAULT_VALUE_INIT_ZERO                    {0, 0}
#define FIRMWARE_UPDATE_INIT_ZERO                {false, SW_VERSION_INIT_ZERO, 0}
#define FIRMWARE_DOWNLOAD_INIT_ZERO              {0, 0, {{NULL}, NULL}}
#define EMETER_TIMESTAMP_INIT_ZERO               {0, 0}
#define HEARTBEAT_INIT_ZERO                      {false, FAULT_VALUE_INIT_ZERO}
#define TEMPERATURE_INIT_ZERO                    {0}
#define EMPTY_INIT_ZERO                          {0}

/* Field tags (for use in manual encoding/decoding) */
#define CLASS_B_DETAILED_FAULTS_FAULTS_TAG       1
#define APP_DETAILED_FAULTS_FAULTS_TAG           1
#define SW_VERSION_MAJOR_TAG                     1
#define SW_VERSION_MINOR_TAG                     2
#define SW_VERSION_HOTFIX_TAG                    3
#define HW_VERSION_VERSION_TAG                   1
#define FAULT_VALUE_CLASS_B_FAULT_TAG            1
#define FAULT_VALUE_APP_FAULT_TAG                2
#define FIRMWARE_UPDATE_FW_VERSION_TAG           1
#define FIRMWARE_UPDATE_IMAGE_SIZE_TAG           2
#define FIRMWARE_DOWNLOAD_IMAGE_OFFSET_TAG       1
#define FIRMWARE_DOWNLOAD_PACKET_ID_TAG          2
#define FIRMWARE_DOWNLOAD_IMAGE_TAG              3
#define EMETER_TIMESTAMP_UNIX_TIME_TAG           1
#define EMETER_TIMESTAMP_BOOT_TIME_TAG           2
#define HEARTBEAT_FAULT_VALUE_TAG                1
#define TEMPERATURE_TMP_TAG                      1

/* Struct field encoding specification for nanopb */
#define CLASS_B_DETAILED_FAULTS_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UENUM,    faults,            1)
#define CLASS_B_DETAILED_FAULTS_CALLBACK NULL
#define CLASS_B_DETAILED_FAULTS_DEFAULT NULL

#define APP_DETAILED_FAULTS_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UENUM,    faults,            1)
#define APP_DETAILED_FAULTS_CALLBACK NULL
#define APP_DETAILED_FAULTS_DEFAULT NULL

#define SW_VERSION_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2) \
X(a, STATIC,   SINGULAR, UINT32,   hotfix,            3)
#define SW_VERSION_CALLBACK NULL
#define SW_VERSION_DEFAULT NULL

#define HW_VERSION_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1)
#define HW_VERSION_CALLBACK NULL
#define HW_VERSION_DEFAULT NULL

#define FAULT_VALUE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   class_b_fault,     1) \
X(a, STATIC,   SINGULAR, UINT32,   app_fault,         2)
#define FAULT_VALUE_CALLBACK NULL
#define FAULT_VALUE_DEFAULT NULL

#define FIRMWARE_UPDATE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fw_version,        1) \
X(a, STATIC,   SINGULAR, UINT32,   image_size,        2)
#define FIRMWARE_UPDATE_CALLBACK NULL
#define FIRMWARE_UPDATE_DEFAULT NULL
#define firmware_update_t_fw_version_MSGTYPE sw_version_t

#define FIRMWARE_DOWNLOAD_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   image_offset,      1) \
X(a, STATIC,   SINGULAR, UINT32,   packet_id,         2) \
X(a, CALLBACK, REPEATED, UINT32,   image,             3)
#define FIRMWARE_DOWNLOAD_CALLBACK pb_default_field_callback
#define FIRMWARE_DOWNLOAD_DEFAULT NULL

#define EMETER_TIMESTAMP_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   unix_time,         1) \
X(a, STATIC,   SINGULAR, UINT32,   boot_time,         2)
#define EMETER_TIMESTAMP_CALLBACK NULL
#define EMETER_TIMESTAMP_DEFAULT NULL

#define HEARTBEAT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fault_value,       1)
#define HEARTBEAT_CALLBACK NULL
#define HEARTBEAT_DEFAULT NULL
#define heartbeat_t_fault_value_MSGTYPE fault_value_t

#define TEMPERATURE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    tmp,               1)
#define TEMPERATURE_CALLBACK NULL
#define TEMPERATURE_DEFAULT NULL

#define EMPTY_FIELDLIST(X, a) \

#define EMPTY_CALLBACK NULL
#define EMPTY_DEFAULT NULL

extern const pb_msgdesc_t class_b_detailed_faults_t_msg;
extern const pb_msgdesc_t app_detailed_faults_t_msg;
extern const pb_msgdesc_t sw_version_t_msg;
extern const pb_msgdesc_t hw_version_t_msg;
extern const pb_msgdesc_t fault_value_t_msg;
extern const pb_msgdesc_t firmware_update_t_msg;
extern const pb_msgdesc_t firmware_download_t_msg;
extern const pb_msgdesc_t emeter_timestamp_t_msg;
extern const pb_msgdesc_t heartbeat_t_msg;
extern const pb_msgdesc_t temperature_t_msg;
extern const pb_msgdesc_t empty_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CLASS_B_DETAILED_FAULTS_FIELDS &class_b_detailed_faults_t_msg
#define APP_DETAILED_FAULTS_FIELDS &app_detailed_faults_t_msg
#define SW_VERSION_FIELDS &sw_version_t_msg
#define HW_VERSION_FIELDS &hw_version_t_msg
#define FAULT_VALUE_FIELDS &fault_value_t_msg
#define FIRMWARE_UPDATE_FIELDS &firmware_update_t_msg
#define FIRMWARE_DOWNLOAD_FIELDS &firmware_download_t_msg
#define EMETER_TIMESTAMP_FIELDS &emeter_timestamp_t_msg
#define HEARTBEAT_FIELDS &heartbeat_t_msg
#define TEMPERATURE_FIELDS &temperature_t_msg
#define EMPTY_FIELDS &empty_t_msg

/* Maximum encoded size of messages (where known) */
/* FirmwareDownload_size depends on runtime parameters */
#define APP_DETAILED_FAULTS_SIZE                 64
#define CLASS_B_DETAILED_FAULTS_SIZE             64
#define EMETER_TIMESTAMP_SIZE                    12
#define EMPTY_SIZE                               0
#define FAULT_VALUE_SIZE                         12
#define FIRMWARE_UPDATE_SIZE                     26
#define HEARTBEAT_SIZE                           14
#define HW_VERSION_SIZE                          6
#define SW_VERSION_SIZE                          18
#define TEMPERATURE_SIZE                         5
#define TYPES_PB_H_MAX_SIZE                      CLASS_B_DETAILED_FAULTS_SIZE

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
