/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CLASS_B_DETAILED_FAULTS, class_b_detailed_faults_t, AUTO)


PB_BIND(APP_DETAILED_FAULTS, app_detailed_faults_t, AUTO)


PB_BIND(SW_VERSION, sw_version_t, AUTO)


PB_BIND(HW_VERSION, hw_version_t, AUTO)


PB_BIND(FAULT_VALUE, fault_value_t, AUTO)


PB_BIND(FIRMWARE_UPDATE, firmware_update_t, AUTO)


PB_BIND(FIRMWARE_DOWNLOAD, firmware_download_t, AUTO)


PB_BIND(EMETER_TIMESTAMP, emeter_timestamp_t, AUTO)


PB_BIND(HEARTBEAT, heartbeat_t, AUTO)


PB_BIND(TEMPERATURE, temperature_t, AUTO)


PB_BIND(EMPTY, empty_t, AUTO)



















